org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/CoverageTransformerTest.java, org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/CoverageTransformer.java, org.jacoco.doc/docroot/doc/changes.html
Related to #35 but it seems to still happen.
This project reproduces the issue: https://github.com/henri-tremblay/jacocomockit
When the line in the readme is executed, you will get this exception:
`java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)`
jmockit 1.14 and jacoco 0.7.2.201409121644 is used
=> Conflict between jmockit and jacoco

org.jacoco.ant.test/src/org/jacoco/ant/InstrumentTaskTest.xml, org.jacoco.ant.test/src/org/jacoco/ant/ReportTaskLocaleTest.java, org.jacoco.ant/src/org/jacoco/ant/ReportTask.java, org.jacoco.doc/docroot/doc/ant.html, org.jacoco.doc/docroot/doc/changes.html
The html elemet of the jacoco report ant task supports the 'locale' attribute. Unfortunately, there's currently no way to configure a Locale for a specific country, since ant seems to convert the String from the ant file to a Locale by invoking the constructor with one String argument, which only allows selection of language, but not of country.
To allow any Locale to be configured, you could e.g. invoke Locale#forLanguageTag.
To test this, you can use e.g. 'de' (German) and 'de-CH' (German (Switzerland)), which use different number formats, even though the language is the same.
=> Html formatter of report ant task only supports basic locales

org.jacoco.ant/src/org/jacoco/ant/AbstractCoverageTask.java, org.jacoco.core.test/src/org/jacoco/core/runtime/AgentOptionsTest.java, org.jacoco.core/src/org/jacoco/core/runtime/AgentOptions.java, org.jacoco.doc/docroot/doc/changes.html
Hello,
At apache lucene we use carrot labs junit4 (http://labs.carrotsearch.com/randomizedtesting-junit4.html) which spawns multiple JVMs to make use of all of our cpus.
The `jacoco:agent` task made this very easy to integrate, but there was one trick, if you try to change the destination file, the setter always converts it to an absolute path (https://github.com/jacoco/jacoco/blob/master/org.jacoco.ant/src/org/jacoco/ant/AbstractCoverageTask.java#L74). Is this intentional?
It seems a little confusing since the default (jacoco.exec) is actually a relative path, but its impossible to set any relative path other than the default since the setter does this conversion.
For us its important that each jvm get a separate file (the easiest way to do that is a relative path), when we create our …
=> destfile agent parameter should be absolute also for default value

org.jacoco.doc/docroot/doc/ant.html
Jacoco (0.6.2) does not work as expected when the following ant configuration is used:
&lt;jacoco:coverage append="false"&gt;
&lt;junit fork="true" forkMode="perTest"&gt;
...
&lt;/junit&gt;
&lt;/jacoco:coverage&gt;
It seems that jacoco dumps its execution data in that case after the execution of each test and as append="false" silently overrides the data from the previous run. 
The documentation says that one should use forkMode="once" to improve performance, but does not note that the above combination does not work.
=> Combination of append="false" and junit forkMode="perTest" does not work

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.examples.test/pom.xml, org.jacoco.examples.test/src/org/jacoco/examples/MBeanClientTest.java, org.jacoco.examples/src/org/jacoco/examples/MBeanClient.java
* JavaDoc is outdated - there is no "mbean" output mode
* IProxy:
* method ```byte[] dump(boolean reset)``` should match corresponding method from IAgent, which is ```void dump(boolean reset)```
* method ``` byte[] getExecutionData(boolean reset)``` should be added
* to avoid such issues consider execution of example as part of build
=> Fix MBeanClient example

org.jacoco.core.test/src/org/jacoco/core/data/ExecutionDataReaderWriterTest.java, org.jacoco.core.test/src/org/jacoco/core/data/IncompatibleExecDataVersionExceptionTest.java, org.jacoco.core/src/org/jacoco/core/data/ExecutionDataReader.java, org.jacoco.core/src/org/jacoco/core/data/IncompatibleExecDataVersionException.java, org.jacoco.doc/docroot/doc/changes.html
Speaking on behalf of @benzonico, who maintains JaCoCo integration with SonarQube:
> "java.io.IOException: Incompatible version 1007."
> is not user-friendly.
Indeed, this message is hard for understanding by end-users, while it can reach them during attempt to read old dump file. See for example discussion http://stackoverflow.com/questions/30459260/jacoco-sonarqube-incompatible-version-1007
=> Improve error message in case of reading of old dump file

org.jacoco.core.test/src/org/jacoco/core/data/ExecutionDataStoreTest.java, org.jacoco.core/src/org/jacoco/core/data/ExecutionDataStore.java, org.jacoco.doc/docroot/doc/changes.html
Hi guys,
I'm having a problem with RuntimeData and specifically with ExecutionDataStore. The data store has a map: **Map<Long, ExecutionData> entries** which causes a concurrent access a problem with the following exception:
```java
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
at org.jacoco.agent.rt.internal_c57fe0e.core.data.ExecutionDataStore.accept(ExecutionDataStore.java:167)
at org.jacoco.agent.rt.internal_c57fe0e.core.runtime.RuntimeData.collect(RuntimeData.java:87)
at org.jacoco.agent.rt.internal_c57fe0e.output.MongoDbOutput.writeExecutionData(MongoDbOutput.java:54)
at org.jacoco.agent.rt.internal_c57fe0e.Agent.shutdown(Agent.java:132)
at …
```
=> RuntimeData not thread safe

jacoco-maven-plugin.test/it/it-customize-agent/pom.xml, jacoco-maven-plugin.test/it/it-customize-agent/verify.bsh, jacoco-maven-plugin/src/org/jacoco/maven/AbstractAgentMojo.java, org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/CoverageTransformerTest.java, org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/CoverageTransformer.java, org.jacoco.ant.test/src/org/jacoco/ant/AgentTaskTest.xml, org.jacoco.ant/src/org/jacoco/ant/AbstractCoverageTask.java, org.jacoco.core.test/src/org/jacoco/core/runtime/AgentOptionsTest.java, org.jacoco.core/src/org/jacoco/core/runtime/AgentOptions.java, org.jacoco.doc/docroot/doc/agent.html, org.jacoco.doc/docroot/doc/ant.html, org.jacoco.doc/docroot/doc/changes.html
Version info:
Gradle 2.2.1
Android Gradle plugin 1.0.1
Robolectric Gradle plugin 0.14.1
JUnit 4.10
Robolectric 2.4
Setting up a simple test using a configuration like:
```groovy
apply plugin: 'jacoco'
jacoco.toolVersion = project.property('jacocoVersion')
```
and running my unit tests with:
$ ./gradlew -PjacocoVersion=0.7.1.+ clean :testDebug :jacocoTestDebugReport
...
$ ls -l build/jacoco/testDebug.exec
-rw-r--r--+ 1 jhansche  staff  278218 Feb 26 16:45 build/jacoco/testDebug.exec
$ strings build/jacoco/testDebug.exec | wc -l
4325
This all works correctly, and I get a proper JaCoCo report generated.  Changing **nothing else** but the `toolVersion`, however, breaks the execution data that is gathered:
$ ./gradlew -PjacocoVersion=0.7.4-SNAPSHOT clean :testDebug :jacocoTestDebugReport
...
$ …
=> >= 0.7.3 breaks Gradle + JUnit + Robolectric coverage (Android)

jacoco-maven-plugin/src/org/jacoco/maven/CheckMojo.java
I have a problem with JaCoCo  maven plugin configuration when I'm trying to  specify finer-grained thresholds for certain classes within rules.
When we use Cobertura maven plugin, for example, we can specify finer-grained thresholds for certain classes using regular expressions.
For example:
```xml
<regex><pattern>.*.checkstyle.AnnotationUtility</pattern><branchRate>60</branchRate><lineRate>60</lineRate></regex>
```
In accordance with JaCoCo maven plugin [documentation for ```jacoco:check```](http://www.eclemma.org/jacoco/trunk/doc/check-mojo.html), we can also do this if we write the rule for every class with  ``` <include>``` tag in configuration for JaCoCo maven plugin (in pom.xml).
For example:
```xml
<configuration>
<haltOnFailure>true</haltOnFailure>  // < ---- Halt the build if any …
```
=> Finer-grained thresholds for certain classes

org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/output/TcpClientOutputTest.java, org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/output/TcpConnectionTest.java, org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/output/TcpServerOutputTest.java, org.jacoco.core.test/src/org/jacoco/core/data/ExecutionDataReaderWriterTest.java, org.jacoco.core.test/src/org/jacoco/core/data/ExecutionDataTest.java, org.jacoco.core.test/src/org/jacoco/core/tools/ExecFileLoaderTest.java, org.jacoco.core/src/org/jacoco/core/data/ExecutionData.java, org.jacoco.core/src/org/jacoco/core/data/ExecutionDataWriter.java, org.jacoco.doc/docroot/doc/changes.html
On the mailing list it was proposed to not dump empty probe arrays to execution data files:
https://groups.google.com/forum/?fromgroups=#!topic/jacoco/wQhTVf2zEtI
In case of repeated dumps (per-test coverage) this can lead to a significant performance improvement:
* test time: 12hrs -> 1hr
* jacoco.exec size: 93GB -> 1GB
Within JaCoCo there is no use for empty probe arrays vs. non existing ExecutionData entries. Therefore there is no need to dump such entries.
=> Don't write empty probe arrays to exec files

jacoco-maven-plugin/pom.xml
Currently jacoco-maven-plugin depends on plexus-utils 1.5.6. It seems when maven decides to really use that version, building a report fails:
```
[INFO] --- jacoco-maven-plugin:0.7.4.201502262128:report (default-report) @ core ---
Mar 5, 2015 4:55:49 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: org.apache.maven.doxia.siterenderer.DefaultSiteRenderer
java.lang.NoClassDefFoundError: org/codehaus/plexus/util/AbstractScanner
at java.lang.Class.getDeclaredConstructors0(Native Method)
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2545)
at java.lang.Class.getDeclaredConstructors(Class.java:1903)
at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBi …
```
=> jacoco-maven-plugin depends on too old plexus-utils

org.jacoco.core.test/src/org/jacoco/core/data/ExecutionDataReaderWriterTest.java, org.jacoco.core/src/org/jacoco/core/data/ExecutionDataReader.java, org.jacoco.doc/docroot/doc/changes.html
As proposed here we should not ignore EOFExceptions in case exec files are truncated somewhere in the middle: https://groups.google.com/d/msg/jacoco/qby-WuQp194/iFnx2fAHBAAJ
=> Improve EOF handling for exec files

org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/CoverageTransformerTest.java, org.jacoco.core.test/src/org/jacoco/core/runtime/ModifiedSystemClassRuntimeTest.java
Currently compilation of tests fails with JDK 9 >= b111.
@marchof do you have an ideas of how we can resolve this?
I can imagine following options:
1. start using mocking framework such as Mockito
2. conditional compilation of different mocks for pre JDK 9 and post JDK 9 using separate module
3. remove this test
=> Fix compilation with JDK 9 >= b111

jacoco-maven-plugin/src/org/jacoco/maven/FileFilter.java, org.jacoco.core.test/src/org/jacoco/core/runtime/ModifiedSystemClassRuntimeTest.java
Remove now unnecessary `supresswarnings` tags after #292 has been merged.
=> Fix compiler warning after plexus-utils upgrade

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/ReportPageTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/SessionsPageTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/SourceFilePageTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/resources/ResourcesTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/table/BarColumnTest.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/SessionsPage.java, org.jacoco.report/src/org/jacoco/report/internal/html/resources/Resources.java
https://github.com/github/maven-plugins/issues/112
JaCoCo version: 0.7.6.201602180812
Operating system: Windows/gitshell 
Tool integration: Maven (github-site plugin)
Reports display correctly on github site. 
The .resources directory is not deployed. 
I have raised an issue with the github/maven-plugins project 
https://github.com/github/maven-plugins/issues/112
however the problem may well not be solvable by them. 
The root cause is that some software, arguably correctly, overlooked a directory starting with a dot. 
Your resources directory should not be a hidden directory. 
Please consider renaming it to resources.
=> ".resources" directory causes problems for github pages

jacoco-maven-plugin.test/it/it-report-aggregate/verify.bsh, org.jacoco.build/pom.xml
We should update the versions of our build plugins. I came accross this issue while trying to build JaCoCo on Windows:
https://issues.apache.org/jira/browse/MNG-5792
=> Fix build on Windows

org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.doc/docroot/doc/changes.html
Add location to `IOException` thrown from
1. `zip.getNextEntry()` in `analyzeZip`
2. `new GZIPInputStream(input)` in `analyzeGzip`
2. `Pack200Streams.unpack(input)` in `analyzePack200`
=> Provide more context information when unable to read input during analysis

jacoco-maven-plugin.test/it/it-java9/invoker.properties, jacoco-maven-plugin.test/it/it-java9/pom.xml, jacoco-maven-plugin.test/it/it-java9/src/main/java/Example.java, jacoco-maven-plugin.test/it/it-java9/src/test/java/ExampleTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/ContentTypeDetectorTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ClassFileVersionsTest.java, org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.core/src/org/jacoco/core/internal/ContentTypeDetector.java, org.jacoco.core/src/org/jacoco/core/internal/Java9Support.java, org.jacoco.core/src/org/jacoco/core/runtime/ModifiedSystemClassRuntime.java, org.jacoco.doc/docroot/doc/changes.html
https://bugs.openjdk.java.net/browse/JDK-8150011
=> Support Java 9 class file format

.travis.sh, jacoco-maven-plugin/pom.xml, jacoco-maven-plugin/src/org/jacoco/maven/AbstractAgentMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/AbstractJacocoMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/AbstractReportMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/AgentITMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/AgentMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/CheckMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/DumpMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/InstrumentMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/MergeMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/ReportITMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/ReportMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/RestoreMojo.java, jacoco/pom.xml
Currently with JDK 9 EA creation of javadoc for jacoco-maven-plugin fails with messages like `unknown tag: requiresProject`.
This problem should vanish, if we'll use annotations - http://maven.apache.org/plugin-tools/maven-plugin-plugin/examples/using-annotations.html And anyway this is a good modernization of code.
=> Use Maven Plugin Tools Java Annotations

.appveyor.yml, org.jacoco.core.test/.classpath, org.jacoco.core.test/pom.xml, org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/InterfaceDefaultMethodsTest.java, org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/LambdaExpressionsTest.java, org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/LambdaInInterfaceTest.java, org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/targets/InterfaceDefaultMethodsTarget.java, org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/targets/LambdaExpressionsTarget.java, org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/targets/LambdaInInterfaceTarget.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/Source.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/SourceTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
Currently "-Dbytecode.version=1.8" should be specified to run build using JDK 8, whereas would be better to use just "mvn clean install".
=> Build with JDK 8 should not require additional arguments

jacoco-maven-plugin/src/org/jacoco/maven/AgentMojo.java
From https://groups.google.com/d/msg/jacoco/ugbiYAbCDA0/1hhdZTPfs7wJ
> You might want to update the documentation at http://www.eclemma.org/jacoco/trunk/doc/prepare-agent-mojo.html
```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-surefire-plugin</artifactId>
<configuration>
</configuration>
</plugin>
```
Indeed, it seems to properly work while defining argLine within the configuration tag using the @{...} syntax: http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine
=> Update documentation of prepare-agent mojo

jacoco-maven-plugin/src/org/jacoco/maven/MergeMojo.java
JaCoCo version: 7.7.-SNAPSHOT
http://eclemma.org/jacoco/trunk/doc/merge-mojo.html
gives 
```
<fileSets>
<fileSet implementation="org.apache.maven.shared.model.fileset.FileSet">
<directory>${project.parent.build.directory}</directory>
<includes>
<include>*.exec</include>
</includes>
</fileSet>
</fileSets>
```
A simple cut and paste into a project without a parent results in a null pointer, the example would be better as: 
```
<fileSets>
<fileSet implementation="org.apache.maven.shared.model.fileset.FileSet">
<directory>${project.build.directory}</directory>
<includes>
<include>*.exec</include>
</includes>
</fileSet>
</fileSets>
```
=> Example in documentation uses possible null parent

jacoco-maven-plugin.test/it/it-report-aggregate/report/src/test/java/packagereport/ReportTest.java, jacoco-maven-plugin.test/it/it-report-aggregate/verify.bsh, jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java
JaCoCo version: 0.7.7-SNAPSHOT
Operating system: Windows
Tool integration: Maven
The maven goal report-aggregate doesn't read the exec file in the executing project.
When an integration-test module IT has collected the coverage data and stored the result to IT/target/jacoco.exec, the report generation by report-aggregate reads all the jacoco.exec files of all dependant projects in the reactor but not the file in the IT module itself.
Since a module isn't dependant by itself in maven, in the method findDependencies there should be the statement
`result.add(this.project);`
Another solution could be, to redesign this goal to walk not thru the depends but thru the submodules like aggregated reports of other tools, so the report will be on the top level of the generated site.
=> maven goal report-aggregate doesn't use it's own measurement 

jacoco-maven-plugin.test/it/it-report-aggregate-customization/child1/pom.xml, jacoco-maven-plugin.test/it/it-report-aggregate-customization/child1/src/main/java/package1/Example1.java, jacoco-maven-plugin.test/it/it-report-aggregate-customization/child1/src/test/java/package1/Example1Test.java, jacoco-maven-plugin.test/it/it-report-aggregate-customization/child2/pom.xml, jacoco-maven-plugin.test/it/it-report-aggregate-customization/child2/src/main/java/package2/Example2.java, jacoco-maven-plugin.test/it/it-report-aggregate-customization/child2/src/test/java/package2/Example2Test.java, jacoco-maven-plugin.test/it/it-report-aggregate-customization/pom.xml, jacoco-maven-plugin.test/it/it-report-aggregate-customization/report/pom.xml, jacoco-maven-plugin.test/it/it-report-aggregate-customization/verify.bsh, jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java
JaCoCo version: 0.7.7-SNAPSHOT
Operating system: Windows
Tool integration: Maven
The property dataFileIncludes in the report-aggregate can't be set by the pom file due to a known bug in maven:
[see here](https://issues.apache.org/jira/browse/MNG-5440?jql=project%20%3D%20MNG%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22%40Parameter%22%20ORDER%20BY%20priority%20DESC)
To fix this by a workaround, the default-value has to been removed from the parameter and access to it should be done by a getter which will set the default if the value is always null
=> Property dataFileIncludes in report-aggregate is not changeable by pom due to known maven bug

org.jacoco.ant.test/src/org/jacoco/ant/DumpTaskTest.xml
This PR covers case described in https://github.com/jacoco/jacoco/pull/300#issuecomment-221838166
=> Get rid of DNS request in DumpTaskTest

org.jacoco.doc/docroot/doc/ant.html, org.jacoco.doc/docroot/doc/build.html, org.jacoco.doc/docroot/doc/flow.html, org.jacoco.doc/docroot/doc/implementation.html, org.jacoco.doc/docroot/doc/maven.html, org.jacoco.doc/docroot/doc/repo.html
In #401 we forgot to adapt some files in documentation to new location of resources:
=> Fix 0.7.7 regression: broken links to stylesheet and javascript in documentation

jacoco-maven-plugin.test/it/it-customize-agent/pom.xml, jacoco-maven-plugin.test/it/it-customize-agent/src/main/java/Example.java, jacoco-maven-plugin.test/it/it-customize-agent/src/test/java/ExampleTest.java, jacoco-maven-plugin.test/it/it-customize-agent/verify.bsh, jacoco-maven-plugin/src/org/jacoco/maven/ReportMojo.java, org.jacoco.doc/docroot/doc/changes.html
See https://groups.google.com/d/msg/jacoco/XtIKmcuqbo8/LUJIIPLjvLYJ
=> Add user property for parameter "dataFile" of "report" mojo

org.jacoco.core/src/org/jacoco/core/runtime/ModifiedSystemClassRuntime.java, org.jacoco.doc/docroot/doc/implementation.html
* ModifiedSystemClassRuntime doesn't add method starting from commit a942c8949be59f949ec110391d766d1f4856a4e0 in v0.3.2.
* Agent modifies "java.util.UUID" instead of "java.sql.Types" starting from commit 5ff6b2dc7a8a82132fbe3a65e4c86a60a0be8693 in v0.5.0.
=> Fix documentation

jacoco-maven-plugin/META-INF/m2e/lifecycle-mapping-metadata.xml, org.jacoco.doc/docroot/doc/changes.html
=> "m2e/lifecycle-mapping-metadata.xml" should include "report-aggregate"

org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactoryTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/FieldProbeArrayStrategy.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactory.java, org.jacoco.doc/docroot/doc/changes.html
I receive with Java 9 the follow error:
```
java.lang.IncompatibleClassChangeError: Method com.inet.error.ErrorCode.$jacocoInit()[Z must be InterfaceMethodref constant
at com.inet.error.ErrorCode.getMsg(ErrorCode.java)
at com.inet.error.BaseErrorTest.testErrorCodeHasDefaultTranslation(BaseErrorTest.java:16)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:533)
at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter.runTestClass(JUnitTestClassExecuter.java:114)
at …
```
=> java.lang.IncompatibleClassChangeError: Method $jacocoInit()[Z must be InterfaceMethodref constant

.travis.sh, .travis.yml, org.jacoco.build/pom.xml, org.jacoco.core.test/pom.xml, org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/CyclomaticComplexityTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/FramesTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/StructuredLockingTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
Question: Do we need to add a profile for Java 9? Like for the other java versions:
<profile>
<id>jdk18</id>
<activation>
<property>
<name>jdk.version</name>
<value>1.8</value>
</property>
</activation>
<properties>
<jvm.args>-XX:-FailOverToOldVerifier -Xverify:all</jvm.args>
</properties>
</profile>
=> Java 9 Support: Profile for 1.9?

org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactoryTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeCounterTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeCounter.java, org.jacoco.doc/docroot/doc/changes.html
`ProbeCounter.hasMethods` should be true for Java 8 interfaces only in case of presence of non-abstract methods.
=> Do not add useless members into Java 8 interfaces that have only clinit and abstract methods

org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/BadCycleInterfaceTest.java
Our current example of "bad cycles" with interfaces ( https://github.com/jacoco/jacoco/pull/434#issuecomment-239643789 ) - is more a demonstration of correct change of behavior between JDK8 and JDK9 than a correct example of "bad cycles" with interfaces as stated in [JDK-8164302](https://bugs.openjdk.java.net/browse/JDK-8164302). We should add correct example.
=> Update comments about "bad cycles" with interfaces

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/html/table/PercentageColumnTest.java, org.jacoco.report/src/org/jacoco/report/internal/html/table/PercentageColumn.java
As per https://github.com/jacoco/jacoco/issues/449#issuecomment-246319827
=> Use RoundingMode#FLOOR for percentages in HTML report

.github/ISSUE_TEMPLATE.md, LICENSE.md, README.md, org.jacoco.build/pom.xml, org.jacoco.examples/build/pom-it.xml, org.jacoco.examples/build/pom-offline.xml, org.jacoco.examples/build/pom.xml
As we're handing over eclemma.org to Eclipse foundation we should use jacoco.org only in JaCoCo URLs.
=> Use jacoco.org domain

org.jacoco.agent.rt.test/build.properties, org.jacoco.agent.rt/build.properties, org.jacoco.agent.test/build.properties, org.jacoco.agent/build.properties, org.jacoco.ant.test/build.properties, org.jacoco.ant/build.properties, org.jacoco.core.test/build.properties, org.jacoco.core/build.properties, org.jacoco.doc/build.properties, org.jacoco.examples.test/build.properties, org.jacoco.examples/build.properties, org.jacoco.report.test/build.properties, org.jacoco.report/build.properties
Since we fully moved to Maven build and IDE setup build.properties files are obsolete.
=> Remove obsolete build.properties Files

jacoco/pom.xml, org.jacoco.agent.rt/pom.xml, org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/changes.html
The primary use case for signing JaCoCo artifacts was the EclEmma plugin. Next release of EclEmma under Eclipse Foundation umbrella will use JaCoCo bundles from [Eclipse Orbit](http://download.eclipse.org/tools/orbit/downloads/), which signed by eclipse.org anyway. So that no need to sign anymore during our releases.
Initial discussion: https://groups.google.com/d/msg/jacoco-dev/hTLvWPXqaUg/fKoDA3zqBAAJ
=> No need to sign JARs using maven-jarsigner-plugin

org.jacoco.doc/docroot/doc/changes.html
JARs of releases that we we publish into Maven central repository should have major, minor and patch components in version, but not qualifier, i.e. simply `0.7.8`. Qualifier should remain in MANIFEST files.
Initial discussion: https://groups.google.com/d/msg/jacoco-dev/HNWPzop4ZI4/pvmfWsSSCAAJ
=> Simplify numbering of versions

org.jacoco.core.test/src/org/jacoco/core/data/ExecutionDataReaderWriterTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/ClassInstrumenterTest.java, org.jacoco.core.test/src/org/jacoco/core/runtime/RuntimeTestBase.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ClassFileVersionsTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/FramesTest.java, org.jacoco.core/src/org/jacoco/core/JaCoCo.java, org.jacoco.core/src/org/jacoco/core/data/ExecutionDataWriter.java, org.jacoco.core/src/org/jacoco/core/internal/flow/ClassProbesAdapter.java, org.jacoco.core/src/org/jacoco/core/internal/flow/ClassProbesVisitor.java, org.jacoco.core/src/org/jacoco/core/internal/flow/LabelFlowAnalyzer.java, org.jacoco.core/src/org/jacoco/core/internal/flow/MethodProbesAdapter.java, org.jacoco.core/src/org/jacoco/core/internal/flow/MethodProbesVisitor.java, org.jacoco.core/src/org/jacoco/core/internal/flow/MethodSanitizer.java, org.jacoco.core/src/org/jacoco/core/internal/instr/DuplicateFrameEliminator.java, org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeInserter.java, org.jacoco.core/src/org/jacoco/core/runtime/ModifiedSystemClassRuntime.java, org.jacoco.doc/docroot/doc/changes.html
In my case, `ExecutionDataWriter.FORMAT_VERSION` is the problematic constant.  We workaround by using reflection to access the field so that javac won't inline the value from the version of the library we use to compile.
I reviewed the `org.jacoco.doc/target/apidocs/constant-values.html`, and `JaCoCo.ASM_API_VERSION` seemed like the only other constant that was likely to cause similar problems for anyone.
=> Runtime initialize non-constant static finals

.travis.sh, org.jacoco.core.test/src/org/jacoco/core/runtime/URLStreamHandlerRuntimeTest.java
```
Failed to execute goal org.codehaus.groovy.maven:gmaven-plugin:1.0:execute (parse-version) on project org.jacoco.build
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make java.lang.String(char[],int,int,java.lang.Void) accessible: module java.base does not "opens java.lang" to unnamed module @603cabc4
at java.base/jdk.internal.reflect.Reflection.throwInaccessibleObjectException(Reflection.java:427)
at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:201)
at java.base/java.lang.reflect.Constructor.checkCanSetAccessible(Constructor.java:184)
at java.base/java.lang.reflect.Constructor.setAccessible(Constructor.java:177)
at org.codehaus.groovy.reflection.CachedConstructor.<init>(CachedConstructor.java:32)
at …
```
=> Fix build failure with JDK 9 EA b148

org.jacoco.core.test/src/org/jacoco/core/test/validation/ExceptionsTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Target03.java
This adds test case that is described on page http://www.eclemma.org/jacoco/trunk/doc/flow.html :
> ..  implicit exceptions from other instructions than method invocations (e.g. NullPointerException ...
And removes misleading comments
> Currently no coverage at all, as we don't see when a block aborts somewhere in the middle.
from the cases, where we actually see some coverage, when block aborts in the middle.
=> Add missing test case that is described in documentation

org.jacoco.ant/META-INF/MANIFEST.MF, org.jacoco.build/pom.xml, org.jacoco.core.test/META-INF/MANIFEST.MF, org.jacoco.core.test/src/org/jacoco/core/test/validation/ResizeInstructionsTest.java, org.jacoco.core/META-INF/MANIFEST.MF, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.examples/META-INF/MANIFEST.MF, org.jacoco.report/META-INF/MANIFEST.MF
JaCoCo cannot re-calculate stackmap frames as this is an expensive operation and would require knowing the type hierarchy (which is not available). Also ASM default implementation for the type hierarchy actually loads(!) the classes.
Therefore in JaCoCo special care has been taken to incrementally update the stackmap frames during instrumentation.
It has been reported that the stackmap frame are re-calculated anyways is special situations, stack trace:
```
java.lang.ClassNotFoundException: javax.servlet.jsp.tagext.BodyContent
at org.jacoco.asm.ClassWriter.getCommonSuperClass(Unknown Source)
at org.jacoco.asm.ClassWriter.a(Unknown Source)
at org.jacoco.asm.Frame.a(Unknown Source)
at org.jacoco.asm.Frame.a(Unknown Source)
at org.jacoco.asm.MethodWriter.visitMaxs(Unknown Source)
at …
```
=> Frames are re-calculated for large methods

org.jacoco.core.test/src/org/jacoco/core/test/validation/ExceptionsTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ImplicitDefaultConstructorTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/PrivateEmptyDefaultConstructorTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Target03.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Target05.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Target06.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Target07.java
There are some unused line markers in validation tests. IMO either they should be removed as they are misleadingly look like important for test, either assertions should be added.
=> Add missing assertions

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java
For some experimental work I tried to implement addition of probe at beginning of method and had hard time to understand inconsistent failures in `MethodAnalyzerTest` - while some tests were failing as expected, others were passing.
Turned out that this was caused by the fact that `MethodAnalyzerTest` violates ASM API - according to [JavaDoc]( http://static.javadoc.io/org.ow2.asm/asm/5.2/org/objectweb/asm/MethodVisitor.html) of `MethodVisitor`:
> visitLineNumber methods must be called after the labels passed as arguments have been visited
As consequence test is less realistic, because simulates behavior that is different from the case when class is loaded from bytecode. Should be noted that such violation is not a big problem to generate bytecode. To demonstrate this asymmetry:
```java …
```
=> MethodAnalyzerTest should not violate contract of ASM API

org.jacoco.doc/docroot/index.html
Currently they point on non existing files. And this is regression that was introduced in version 0.7.7 by commit c181f60ce08ec9b0a6f59a2391c33c41bca8f1c0.
=> Fix broken links to CSV and XML coverage reports in distribution

org.jacoco.core.test/src-java8/org/jacoco/core/test/validation/BadCycleInterfaceTest.java
`BadCycleInterfaceTest` currently fails on 1.8.0_152-ea-b01, because fix for the bug [JDK-8163969](https://bugs.openjdk.java.net/browse/JDK-8163969) that we found has been backported to JDK 8 - [JDK-8167607](https://bugs.openjdk.java.net/browse/JDK-8167607).
=> Fix BadCycleInterfaceTest for JDK 8u152

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/ClassAnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/EnumImplicitMethodsTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/EnumImplicitMethods.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassAnalyzer.java, org.jacoco.doc/docroot/doc/changes.html
I propose to do a baby step in story of filtering by excluding enum methods `values` and `valueOf` from reports.
=> Exclude enum methods "values" and "valueOf" from reports

org.jacoco.core.test/src/org/jacoco/core/test/validation/ControlStructuresTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
Use new `ValidationTestBase.isJDKCompiler` constant for missing assertions.
=> Use new compiler detection facility

org.jacoco.core.test/src/org/jacoco/core/test/validation/ControlStructuresTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/targets/Target01.java
As noted by @Godin we actually saw a side effect in #503. To avoid such side effects the tested structures should better be tested in separate methods.
=> Separate structure constructs in validation tests 

org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/IFilter.java
Due to our compiler settings every public method should have JavaDoc. Sorry for overlooking this during the review.
=> Document IFilter.filter() to make org.jacoco.core warning free

org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/CoverageTransformerTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.doc/docroot/doc/changes.html
In #400 we updated `Analyzer`, but not `Instrumenter`.
So that for example for the same `broken.zip` `Analyzer.analyzeAll` produces:
```
java.io.IOException: Error while analyzing /tmp/jacoco/in/broken.zip@brokenentry.txt.
```
while `Instrumenter.instrumentAll`:
```
java.util.zip.ZipException: invalid distance too far back
```
This difference is also visible between Ant tasks `report` and `instrument` when they used for archives that contain corrupted nested archives - in a stack trace in case of `report` name of a nested corrupted archive is shown, while in case of `instrument` not.
=> Provide more context information when unable to read input during instrumentation

org.jacoco.doc/docroot/doc/faq.html
I have a project which is validating html content using nu.validator in unit tests. Works fine but when I instrument it with jacoco it's going nuts.
I end up with the following java.lang.StackOverflowError:
```
java.lang.StackOverflowError
at com.thaiopensource.relaxng.impl.DuplicateAttributeDetector$Alternative.<init>(Unknown Source)
at com.thaiopensource.relaxng.impl.DuplicateAttributeDetector$Alternative.<init>(Unknown Source)
at com.thaiopensource.relaxng.impl.DuplicateAttributeDetector.startChoice(Unknown Source)
at com.thaiopensource.relaxng.impl.ChoicePattern.checkRestrictions(Unknown Source)
at com.thaiopensource.relaxng.impl.ChoicePattern.checkRestrictions(Unknown Source)
at com.thaiopensource.relaxng.impl.ChoicePattern.checkRestrictions(Unknown Source)
at …
```
=> Improve Documentation about StackOverflowError Situations

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/PrivateEmptyNoArgConstructorFilterTest.java, org.jacoco.core.test/src/org/jacoco/core/test/filter/ConstructorTest.java, org.jacoco.core.test/src/org/jacoco/core/test/filter/SyntheticTest.java, org.jacoco.core.test/src/org/jacoco/core/test/filter/targets/Constructor.java, org.jacoco.core.test/src/org/jacoco/core/test/filter/targets/Synthetic.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/PrivateEmptyDefaultConstructorTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AbstractMatcher.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/PrivateEmptyNoArgConstructorFilter.java, org.jacoco.doc/docroot/doc/changes.html
After reflecting for some time, I believe that we can unconditionally safely ignore private empty constructors that do not have arguments. Even despite the fact that they relate to a source code and not generated by compiler. Note that this will completely exclude from report unused classes that have only such constructor, but anyway revealing of those is not a job of code coverage tool.
This will also improve report for JaCoCo itself.
=> Exclude from a report private empty constructors that do not have arguments

jacoco-maven-plugin/src/org/jacoco/maven/CheckMojo.java, org.jacoco.doc/docroot/doc/ant.html, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/check/LimitTest.java, org.jacoco.report/src/org/jacoco/report/check/Limit.java
=> Support limit ratios as percents

org.jacoco.core.test/src/org/jacoco/core/tools/ExecDumpClientTest.java, org.jacoco.core/src/org/jacoco/core/tools/ExecDumpClient.java, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.examples/src/org/jacoco/examples/ExecutionDataClient.java
Ant and Maven `dump` commands use the `ExecDumpClient` class from the `org.jacoco.core` module. This utility does not evaluate the response status after sending a `dump` request. If the remote closes the connection without sending a response this is silently ignored.
Expected behavior is that a `IOException` is thrown when a `dump` request is not answered.
=> ExecDumpClient should report error when no execution data is retrieved

org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.core/src/org/jacoco/core/internal/Java9Support.java, org.jacoco.doc/docroot/doc/changes.html
=> Method Analyzer.analyzeClass(InputStream, String) as others should provide context information when unable to read input during analysis

org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/InstrumentTest.java, org.jacoco.cli/src/org/jacoco/cli/internal/commands/Instrument.java
```
java -jar jacococli.jar instrument Example.class --dest instrumented
```
leads to
```
Exception in thread "main" java.lang.NullPointerException
at org.jacoco.cli.internal.commands.Instrument.instrument(Instrument.java:78)
at org.jacoco.cli.internal.commands.Instrument.instrumentRecursive(Instrument.java:72)
at org.jacoco.cli.internal.commands.Instrument.execute(Instrument.java:56)
at org.jacoco.cli.internal.Main.execute(Main.java:89)
at org.jacoco.cli.internal.Main.main(Main.java:104)
```
while
```
java -jar jacococli.jar instrument Example.class --dest ./instrumented
```
works and produces file `/tmp/./instrumented`
```
[INFO] 1 classes instrumented to /tmp/./instrumented.
```
however description of `--dest` option:
```
--dest <dir>  : path to write instrumented Java classes to
```
=> NullPointerException in CLI when instrumenting single class

org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/PreMain.java, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/implementation.html
As was discussed in #551 : `java/lang/UnknownError` is intended for use by Virtual Machine and in rare situations, so seems that probability that it is used by other Java agents is lower compared to `java/util/UUID` and hence we should change code to use it for communication between instrumented classes and agent. In case if even this class is used by other agents, recommendation remains the same - JaCoCo agent should be the first one specified on the command line. Page "Implementation Design" in documentation should be updated accordingly.
=> Reduce chance of conflict with other agents

jacoco-maven-plugin.test/it/setup-parent/invoker.properties, jacoco-maven-plugin/pom.xml, org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/changes.html
```
mvn org.jacoco:jacoco-maven-plugin:0.7.8:help
```
works, while
```
mvn org.jacoco:jacoco-maven-plugin:0.7.9:help
```
fails as well as
```
mvn org.jacoco:jacoco-maven-plugin:0.7.10-SNAPSHOT:help
```
=> Regression in 0.7.9: "help" goal is not available in jacoco-maven-plugin

org.jacoco.doc/docroot/doc/repo.html
In [`repo.html`](http://www.jacoco.org/jacoco/trunk/doc/repo.html) we describe some of the artifacts we deliver to maven. The list should be completed to list all artifacts along with their respective Maven classifiers - see https://github.com/jacoco/jacoco/pull/525#discussion_r117549648
=> Update documentation for published Maven artifacts

org.jacoco.build/pom.xml, org.jacoco.core.test/src-java7/org/jacoco/core/test/filter/TryWithResourcesTest.java
`java.version` in JDK 9 < b175 was `9-ea`, while for >= b175 it is `9`, which causes
```
Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end 3, length 1
at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3116)
at java.base/java.lang.String.substring(String.java:1885)
at org.apache.commons.lang.SystemUtils.getJavaVersionAsFloat(SystemUtils.java:1133)
```
in version of `commons-lang` that is used by some Maven plugins:
* maven-javadoc-plugin - https://issues.apache.org/jira/browse/MJAVADOC-485
* gmaven-plugin
=> Fix build for JDK 9 >= b175

org.jacoco.agent.rt/pom.xml, org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/changes.html
There is no doubts about module names and their usefulness for the following JARs:
* `org.jacoco.core` for `org.jacoco.core-<VERSION>.jar`
* `org.jacoco.report` for `org.jacoco.report-<VERSION>.jar`
* `org.jacoco.ant` for `org.jacoco.ant-<VERSION>.jar`
Also seems that module name is useful for agent (see #545). While there might be debate about its name and name for `org.jacoco.agent-<VERSION>.jar` that contains first one as a resource and whose existence might also be a subject of discussion, we can start with
* `org.jacoco.agent.rt` for `jacocoagent.jar` - consistent with names of packages inside JARs. 
Should also be noted that I don't think that existence of class `com.vladium.emma.RT` in this JAR is a problem - anyway can be solved later when/if it will turn out to be a problem
* …
=> For Java 9 add "Automatic-Module-Name" to manifests of JAR files

org.jacoco.doc/docroot/doc/faq.html
According to documentation of [`java.lang.ClassNotFoundException`](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassNotFoundException.html):
> Thrown when an application tries to load in a class through its string name using:
> * The forName method in class Class.
> * The findSystemClass method in class ClassLoader .
> * The loadClass method in class ClassLoader.
and we do not use directly/explicitly any of them for `org/jacoco/agent/rt/.../Offline` that is part of direct method call. Situation described in FAQ:
```
$ cat <<END > App.java
class App {
public static void main(String[] args) {
}
}
END
$ javac App.java
$ java -jar jacococli.jar instrument App.class --dest instrumented
$ java -cp instrumented App
```
leads to:
```
Exception in thread "main" …
```
=> Improve FAQ about "ClassNotFoundException: org.jacoco.agent[...]Offline"

jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java, org.jacoco.doc/docroot/doc/changes.html
I have an aggregate maven project where one of the projects must be scoped as 'provided'.  I would like it to be still considered for inclusion in the aggregate report.
=> Add Artifact.SCOPE_PROVIDED artifacts to aggregate report

org.jacoco.cli.test/src/org/jacoco/cli/internal/CommandTestBase.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/ClassInfoTest.java, org.jacoco.cli/src/org/jacoco/cli/internal/commands/ClassInfo.java
While analyzing reported issue I extended the `classinfo` command to provide details about every method and line. As this was useful to quickly spot an issue I decided to provide an official option for this.
=> Add --verbose option to classinfo

org.jacoco.examples/src/org/jacoco/examples/MBeanClient.java
=> Description of MBeanClient example should refer to agent option "jmx=true" instead of removed output mode "mbean"

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/flow/InstructionTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java, org.jacoco.core/src/org/jacoco/core/internal/flow/Instruction.java
I propose to do one more baby step in story of filtering - determine covered branches for each instruction. This is non-functional change (in terms of visibility for users), but required for implementation of filter for `finally` blocks to properly merge instructions that cover different branches. This change separated from filter to allow focus on actual implementation of filter rather than on internal mechanics.
=> Yak shaving: determine covered branches for each instruction

org.jacoco.core.test/src-java7/org/jacoco/core/test/filter/targets/StringSwitch.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/StringSwitchJavacFilter.java
During implementation of filter in #596, we made it strict, and today I started to wonder - isn't it too strict to cover cases such as:
```
switch (Objects.requireNonNull(s)) {
case "...":
...
}
```
And actually it works fine! :thumbsup:
Will be better to include this case in test to avoid similar questions in future.
=> Improve test of filter to show that it works even if string in switch represented by complex expression

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodAnalyzer.java
As a follow up to #601 this PR seeks to clean-up the `MethodAnalyzerTest`:
* Use new naming conventions
* cleanup and separate existing tests
* new tests for use cases not yet covered
There are still some opcodes (i.e. `visit()` methods) which are not yet covered.
=> Clean-up MethodAnalyzerTest

org.jacoco.core.test/src/org/jacoco/core/internal/flow/FrameSnapshotTest.java
Follow-up for #606: Consistently use descriptive test names for all tests.
=> Descriptive test names for FrameSnapshotTest

org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.examples/src/org/jacoco/examples/CoreTutorial.java
Will be better to clarify that caller is responsible for closing of streams passed to methods of `Analyzer` and `Instrumenter` - at least by fixing this in `CoreTurorial` example, and ideally also by update of Javadocs.
=> Unclosed streams in CoreTutorial

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/GroovyGeneratedFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AbstractAnnotatedMethodFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/Filters.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/GroovyGeneratedFilter.java, org.jacoco.doc/docroot/doc/changes.html
Hackergarten Bern Session, co-hacked with @aalmiray and @marchof
=> Filter for Groovy generated methods

jacoco-maven-plugin.test/it/it-includes-excludes/pom.xml, jacoco-maven-plugin.test/it/it-java9-offline-instrumentation/pom.xml, jacoco-maven-plugin.test/it/it-multi-module/pom.xml, jacoco-maven-plugin.test/it/it-offline-instrumentation/pom.xml, jacoco-maven-plugin.test/it/it-report-nomatch/pom.xml, jacoco-maven-plugin.test/it/it-report-unreadable-dump/pom.xml, jacoco-maven-plugin.test/it/it-report-without-debug/pom.xml, jacoco-maven-plugin.test/it/it-report-without-dump/pom.xml, org.jacoco.examples/build/pom-offline.xml, org.jacoco.examples/build/pom.xml
Since version 0.6.2 the `report` binds to phase `verify`. No need to specify phase in tests and examples.
=> Remove unnecessary phase definition for report goal

org.jacoco.core/src/org/jacoco/core/data/ExecutionData.java
Previously the behaviour when flag is true was specified twice but not at all when flag is false. (Looks like a typo.)
=> Fix ExecutionData.merge JavaDoc

org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactoryTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactory.java
Given
```
$ mkdir -p src/org/example
$ cat <<END > src/module-info.java
module org.example {
}
END
$ cat <<END > src/org/example/HelloWorld.java
package org.example;
class HelloWorld {
public static void main(String[] args) {
System.out.println("Hello, World");
}
}
END
$ javac -d mods/org.example \
src/module-info.java \
src/org/example/HelloWorld.java
```
after #600 we are able to instrument `module-info.class`
```
$ java -jar jacococli.jar \
instrument mods \
--dest mods-instrumented
```
and after #565 execute instrumented module using `--add-reads`
```
$ java \
--module-path mods-instrumented:jacocoagent.jar \
--add-modules org.jacoco.agent.rt \
--add-reads org.example=org.jacoco.agent.rt \
--module org.example/org.example.HelloWorld
```
however test #608 lacks such execution and …
=> Offline instrumentation should not damage module-info

org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/ClassFileDumper.java, org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/data/CRC64Test.java, org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.core/src/org/jacoco/core/internal/data/CRC64.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactory.java
https://groups.google.com/d/msg/jacoco-dev/uPwM10Ia4Ks/x4CC4hd0CwAJ
```
$ cat <<END > Example.java
class Example {
public static void main(String[] args) {
}
}
END
$ javac -source 9 -target 9 Example.java
$ java -javaagent:jacoco-0.7.9/lib/jacocoagent.jar=includes=Example,destfile=1.exec Example
$ java -javaagent:jacoco-0.7.10-20171220.225235-84/lib/jacocoagent.jar=includes=Example,destfile=2.exec Example
$ java -jar jacoco-0.7.10-20171220.225235-84/lib/jacococli.jar execinfo 1.exec 2.exec
[INFO] Loading exec file 1.exec.
CLASS ID         HITS/PROBES   CLASS NAME
Session "Godins-iMac.lrc.sonarsource.com-2c84a6d3": Thu Dec 21 20:53:29 CET 2017 - Thu Dec 21 20:53:29 CET 2017
2cc2366f70618d57    1 of   2   Example
[INFO] Loading exec file 2.exec.
CLASS ID         HITS/PROBES   CLASS NAME …
```
=> Restore exec files compatibility regarding Java 9 class files

org.jacoco.core.test/src/org/jacoco/core/test/filter/FinallyTest.java
Execution of
```
$ java -version
java version "10-ea" 2018-03-20
Java(TM) SE Runtime Environment 18.3 (build 10-ea+42)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10-ea+42, mixed mode)
$ mvn clean verify -Dbytecode.version=1.9 -Djacoco.skip
```
currently fails on `gotos(org.jacoco.core.test.filter.FinallyTest)`
```
expected:<[emptyCatch.2, catchNotExecuted.2, breakStatement.for, example.2, nested.5, nested.6, breakStatement.2, breakStatement.1]>
but was:<[emptyCatch.2, catchNotExecuted.2, breakStatement.for, example.2, nested.5, breakStatement, nested.6, breakStatement.2]>
```
because [JDK-8180141](https://bugs.openjdk.java.net/browse/JDK-8180141) was fixed.
=> Adjust test to reflect fix of JDK-8180141 in JDK 10

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/EnumEmptyConstructorFilterTest.java, org.jacoco.core.test/src/org/jacoco/core/test/filter/EnumConstructorTest.java, org.jacoco.core.test/src/org/jacoco/core/test/filter/targets/EnumConstructor.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AbstractMatcher.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/EnumEmptyConstructorFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/Filters.java, org.jacoco.doc/docroot/doc/changes.html
=> Add filter for empty constructor without parameters in enum

org.jacoco.doc/docroot/doc/faq.html
No idea whether this actually helps to reduce the spam, but at least we have a clear message publicly available we can refer to in answers.
=> New FAQ entry about release dates.

org.jacoco.core.test/src/org/jacoco/core/internal/instr/InstrSupportTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ClassFileVersionsTest.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactory.java, org.jacoco.doc/docroot/doc/changes.html
JaCoCo version: 0.8.1
Operating system: any
Tool integration: any
Instrument a class with version 1.5 or below.
No stackmap frames are inserted.
When inserting probes for conditional jumps frames are actually inserted. By definition they are ignored by the java runtime but may cause problems with ASM (large methods) or other tools.
This issue was reported on our mailing list: https://groups.google.com/forum/?fromgroups=#!topic/jacoco/O84HGz6AWq4
=> Don't insert stackmap frames into class files with version < 1.6.

org.jacoco.core.test/pom.xml, org.jacoco.core/pom.xml
[Historically we used `asm-debug-all`](https://github.com/jacoco/jacoco/commit/351b20ee84db15e054b01c3a5e7b4234cecad890) due to lack of debug info in other JARs. Starting from [ASM 6.0 other JARs finally have debug info and `asm-debug-all` was removed](https://gitlab.ow2.org/asm/asm/commit/4c449bea1e3fb980238c61d60103fe1be76e77e5). During [upgrade to ASM 6.0](https://github.com/jacoco/jacoco/commit/caa820ed62133f47bacba06ea931bf5d7c43dcd6) dependency on `asm-debug-all` was simply replaced by dependencies on all ASM JARs, while we  use `asm-analysis` and `asm-util` only in tests.
=> Remove unused dependencies on asm-analysis and asm-util in org.jacoco.core

org.jacoco.core.test/src/org/jacoco/core/runtime/WildcardMatcherTest.java, org.jacoco.core/src/org/jacoco/core/runtime/WildcardMatcher.java, org.jacoco.doc/docroot/doc/changes.html
=> Question mark in filter expressions should match exactly one character

org.jacoco.cli.test/src/org/jacoco/cli/internal/MainTest.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/ClassInfoTest.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/DumpTest.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/ExecInfoTest.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/InstrumentTest.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/MergeTest.java, org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/ReportTest.java
As mentioned in out mailing list our CLI tests fail for locales other than english:
https://groups.google.com/d/msg/jacoco/zOw0llfraAM/wMiYu5CUEAAJ
The build should therefore configure english as the default locale.
=> CLI tests should not depend on current locale

org.jacoco.cli/pom.xml
Follow up on https://github.com/jacoco/jacoco/pull/682#issuecomment-395540141
Before this change:
```
$ java -Duser.language=ru -Duser.country=RU -jar org.jacoco.cli/target/org.jacoco.cli-0.8.2-SNAPSHOT-nodeps.jar
Command line interface for JaCoCo.
Usage: java -jar jacococli.jar --help | <command>
<command> : dump|instrument|merge|report|classinfo|execinfo|version
--help    : show help
--quiet   : suppress all output on stdout
Требуется аргумент "<command>"
```
After this change:
```
$ java -Duser.language=ru -Duser.country=RU -jar org.jacoco.cli/target/org.jacoco.cli-0.8.2-SNAPSHOT-nodeps.jar
Command line interface for JaCoCo.
Usage: java -jar jacococli.jar --help | <command>
<command> : dump|instrument|merge|report|classinfo|execinfo|version
--help    : show help
--quiet   : suppress …
```
=> Remove partial localization of CLI

org.jacoco.core.test/src/org/jacoco/core/internal/instr/InstrSupportTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java, org.jacoco.doc/docroot/doc/changes.html
The instrumentation and analysis process expects original, uninstrumented classes. This seems to be a common configuration issue - see #700. Therefore the error message should be improved to be more helpful:
`Cannot process instrumented class X. Please supply original non-instrumented classes.`
=> Improve error message when working on instrumented classes

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/xml/XMLGroupVisitorTest.java, org.jacoco.report.test/src/org/jacoco/report/xml/XMLFormatterTest.java, org.jacoco.report/src/org/jacoco/report/internal/xml/XMLCoverageWriter.java, org.jacoco.report/src/org/jacoco/report/xml/XMLFormatter.java, org.jacoco.report/src/org/jacoco/report/xml/report.dtd
A new attribute should be added to allow mapping source files with secondary classes.
Fixes #701
=> Add new attribute "sourcefilename" to "class" element in XML report

org.jacoco.report/src/org/jacoco/report/xml/XMLFormatter.java
It was probably to late in the night when I rebased #652 on master.
=> Remove unused constants in XMLFormatter

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinLateinitFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AbstractMatcher.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/Filters.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinLateinitFilter.java, org.jacoco.doc/docroot/doc/changes.html
This change adds a new filter for Kotlin lateinit properties by searching in the bytecode for the following sequence of instructions:
```
IFNONNULL ...
LDC "..."
INVOKESTATIC kotlin/jvm/internal/Intrinsics.throwUninitializedPropertyAccessException (Ljava/lang/String;)V
```
and ignoring this sequence if found. 
This approach scans through all instructions in every method found, so maybe it might be an idea to only apply the filter on Kotlin classes.  I haven't run any integration tests to measure the performance impact except for a small Kotlin project to verify results:
**Before:**
**After:**
=> Add filter for Kotlin lateinit properties

org.jacoco.build/pom.xml, org.jacoco.core.test.validation.kotlin/.classpath, org.jacoco.core.test.validation.kotlin/.project, org.jacoco.core.test.validation.kotlin/pom.xml, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinTopLevelFunctionTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinTopLevelFunctionTarget.kt, org.jacoco.core.test.validation/pom.xml, org.jacoco.doc/docroot/doc/build.html
PR #709 contains more/other tests, however
* it was done before #711 and so doesn't execute them on JDKs and bytecode versions other than 8
* these tests require some rework/cleanup
This PR
* allows to compile Kotlin source files into all bytecode versions supported by `kolinc` (6 and 8) 
* and execute them in all JDKs >= 6
* uses more recent version of Kotlin - most recent as of today
* allows addition of new filters and corresponding tests (#704) without waiting cleanup of tests in #709
* adds basic test that utilizes/validates #714
* adds check of presence of license info in Kotlin source files
=> Add module for Kotlin validation tests

org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/EnumImplicitMethodsTest.java, org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/FinallyTest.java, org.jacoco.core.test.validation.java7/src/org/jacoco/core/test/validation/java7/StringSwitchTest.java, org.jacoco.core.test.validation.java7/src/org/jacoco/core/test/validation/java7/TryWithResourcesTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
IMO usage of
https://github.com/jacoco/jacoco/blob/bbee0397a1ff4e39bab42c731531d02cc404fc2b/org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java#L133
is error-prone since it doesn't imply zero number of branches, especially when presence of branch is not obvious like in Kotlin for `when` expressions and `lateinit`. At least I'm constantly stepping on this during implementation of filters, and miss branches that should be filtered out.
=> `assertLine(String, int)` should imply zero number of branches

org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/changes.html
As usual classes of JDK 12 EA already compiled into new bytecode version 56, so that `ModifiedSystemClassRuntime` can't be used without downgrade-upgrade workaround or ASM upgrade.
To notice changes in javac 12 EA unrelated to bytecode version such as #669 or even regressions such as [JDK-8180141](https://bugs.openjdk.java.net/browse/JDK-8180141), one currently need to exclude integration tests which use agent:
```
$ java -version
openjdk version "12-ea" 2019-03-19
OpenJDK Runtime Environment 19.3 (build 12-ea+5)
OpenJDK 64-Bit Server VM 19.3 (build 12-ea+5, mixed mode)
$ mvn -V -B -e clean verify -Dbytecode.version=11 \
-Djacoco.skip \
-pl \!org.jacoco.ant.test,\!jacoco-maven-plugin.test,\!org.jacoco.examples.test,\!org.jacoco.doc,\!jacoco
```
Fortunately ASM 6.2.1 among other bug fixes …
=> Upgrade ASM to 6.2.1

jacoco-maven-plugin/src/org/jacoco/maven/MergeMojo.java
Maven can not convert string specified in command line into `List<FileSet>`.
Fixes #438
=> Remove useless `jacoco.fileSets` from documentation of `MergeMojo`

.travis.sh
In Travis `maven-javadoc-plugin:2.10.4` tries to download some artifacts and causes long build times:
```
...
[INFO] --- maven-javadoc-plugin:2.10.4:jar (attach-javadocs) @ org.jacoco.doc ---
...
[INFO] Downloading from sonatype: https://oss.sonatype.org/content/repositories/releases/org/ow2/asm/asm-commons/6.2.1/asm-commons-6.2.1-javadoc-resources.jar
[INFO] Downloading from sonatype-apache: https://repository.apache.org/releases/org/ow2/asm/asm-commons/6.2.1/asm-commons-6.2.1-javadoc-resources.jar
...
[INFO] JaCoCo :: Documentation ............................ SUCCESS [21:35 min]
...
```
Repositories `sonatype` and `sonatype-apache` are [defined by Travis in its `~/.m2/settings.xml`](https://github.com/travis-ci/travis-cookbooks/blob/b3d510af30ab32835a6738fd6803ee9a57633569/cookbooks/tra …
=> Do not use `~/.m2/settings.xml` provided by Travis

org.jacoco.core/src/org/jacoco/core/runtime/CommandLineSupport.java
- Fix typo `separete` and `combined`
- Make `M_STRIPWHITESPACE ` redable by replacing it with `M_STRIP_WHITESPACE `
- Also for `M_PARSEARGUMENT ` with `M_PARSE_ARGUMENT `
=> Fix Typo issue

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodCoverageCalculatorTest.java
Without following condition all unit tests still pass
https://github.com/jacoco/jacoco/blob/4d4d02e6dbfb17f454bf4579ee13209e9f035154/org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodCoverageCalculator.java#L128
however this condition is important for #763 , so I propose to add test.
=> Add test: computation of lines range should respect ignored instructions

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinInlineTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinInlineTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java
For `inline` function declared at file level and used in class declared in the same file, Kotlin compiler produces SMAP that refers to the same source file by different `SourceFileId`s:
`example.kt`
```
inline fun inlined() {
}
class Callsite {
fun callsite() {
inlined()
}
} // line 8
```
`javap -v -p Callsite.class`
```
...
LineNumberTable:
line 6: 0
line 10: 1
line 7: 2
...
SourceDebugExtension:
SMAP
example.kt
Kotlin
*S Kotlin
*F
+ 1 example.kt
Callsite
+ 2 example.kt
ExampleKt
*L
1#1,9:1
2#2:10
*E
*S KotlinDebug
*F
+ 1 example.kt
Callsite
*L
6#1:10
*E
```
Filter that was implemented in #764 for #763 should be fixed to not filter out the whole class in this case.
=> Fix filtering in case of inlining top level function into class in same file

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/ClassPageTest.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/ClassPage.java
One of common problems already described in [our FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html) and still frequently faced by users - incorrect location of source files, which leads to absence of pages with sources in HTML report:
* https://stackoverflow.com/a/53833558/244993
* https://groups.google.com/d/msg/jacoco/wmwYxLKKn3Q/5AH5qSGBDgAJ
* https://github.com/jacoco/jacoco/issues/787#issuecomment-437578208
* https://github.com/jacoco/jacoco/issues/751#issuecomment-414480178
So I propose to add following message to a page with class methods
```
Source file `org/example/Example.java` was not found during generation of report.
```
=> Show message in HTML report when source file can't be found

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinCoroutineTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/SyntheticFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/SyntheticFilter.java, org.jacoco.doc/docroot/doc/changes.html
Seems that Kotlin compiler generates `synthetic` methods for `private` and `open` suspending functions:
`Example.kt`
```
import kotlinx.coroutines.delay
private suspend fun suspendingFunction(x: Long) {
delay(x) // line 4
}
open class Open {
open suspend fun suspendingFunction(x: Long) {
delay(x) // line 9
}
}
```
`javap -v -p ExampleKt.class`
```
static final java.lang.Object suspendingFunction(long, kotlin.coroutines.Continuation<? super kotlin.Unit>);
descriptor: (JLkotlin/coroutines/Continuation;)Ljava/lang/Object;
flags: ACC_STATIC, ACC_FINAL, ACC_SYNTHETIC
Code:
stack=3, locals=3, args_size=2
0: lload_0
1: aload_2
2: invokestatic  #13                 // Method kotlinx/coroutines/DelayKt.delay:(JLkotlin/coroutines/Continuation;)Ljava/lang/Object;
5: areturn
LocalVariableTable:
Start …
```
=> synthetic methods that represent Kotlin suspend functions should not be ignored

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinCoroutineTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilter.java, org.jacoco.doc/docroot/doc/changes.html
`Example.kt`
```
import kotlinx.coroutines.delay
fun nop() {
}
suspend fun example() { // line 6
delay(0) // line 7
nop()
}
```
`javap -v -p ExampleKt.class`
```
public static final java.lang.Object example(kotlin.coroutines.Continuation<? super kotlin.Unit>);
descriptor: (Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL
Code:
stack=5, locals=4, args_size=1
0: aload_0
1: instanceof    #12                 // class ExampleKt$example$1
4: ifeq          36
7: aload_0
8: checkcast     #12                 // class ExampleKt$example$1
11: astore_2
12: aload_2
13: getfield      #16                 // Field ExampleKt$example$1.label:I
16: ldc           #17                 // int -2147483648
18: iand
19: ifeq          36
22: aload_2
23: dup
24: getfield …
```
=> Update filter for Kotlin suspending functions

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/ClassPageTest.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/ClassPage.java
In addition to #801 another common problem already described in our FAQ and still frequently faced by users - absence of debug information in class files.
This PR adds following messages to a page with class methods:
```
Class files must be compiled with debug information to link with source files.
```
```
Class files must be compiled with debug information to show line coverage.
```
=> Show messages in HTML report when class has no debug information

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/ClassPageTest.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/ClassPage.java
In addition to #801 and #818 another common problem already described in our FAQ and still frequently faced by users - mismatch between executed and analyzed class file.
This PR adds following message to a page with class methods:
```
A different version of class was executed at runtime.
```
=> Show message in HTML report when analyzed class does not match executed

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/AnnotationGeneratedFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/AnnotationGeneratedFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> Extend filtering by annotation name to ones that simply contain Generated

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java
[`createIfBranchMerge` in `MethodAnalyzerTest`](https://github.com/jacoco/jacoco/blob/34afa221fa3102427b04ca44ef827c4ddff2cd0f/org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java#L291-L305) creates following bytecode
```
iload
ifeq l1
nop
l1: return
```
`probe[0]` is inserted for `ifeq` and indicates jump to `l1`
`probe[1]` is inserted before `l1`
`probe[2]` is inserted after `l1`
If dump is not taken in the middle of the method, then
[test `if_branch_merge_should_show_partial_branch_coverage_when_probe_for_second_branch_is_executed`](https://github.com/jacoco/jacoco/blob/34afa221fa3102427b04ca44ef827c4ddff2cd0f/org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java#L335-L344) does not look realistic, because when `probe[1]` is …
=> Fix MethodAnalyzerTest

org.jacoco.agent.rt/pom.xml, org.jacoco.ant/pom.xml, org.jacoco.cli/pom.xml
Thanks to #820 we can benefit from https://issues.apache.org/jira/browse/MSHADE-303 and get rid of warnings
```
[WARNING] Discovered module-info.class. Shading will break its strong encapsulation.
```
=> Get rid of warnings about shading ASM "module-info.class"

jacoco-maven-plugin.test/it/it-check-fails-halt/pom.xml, jacoco-maven-plugin.test/it/it-check-fails-no-halt/pom.xml, jacoco-maven-plugin.test/it/it-check-passes/pom.xml, jacoco-maven-plugin.test/it/it-dump/pom.xml, jacoco-maven-plugin.test/it/it-java9/pom.xml, jacoco-maven-plugin/pom.xml, jacoco-maven-plugin/src/org/jacoco/maven/CheckMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/MergeMojo.java, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/maven.html, org.jacoco.examples/build/pom-it.xml, org.jacoco.examples/build/pom-offline.xml, org.jacoco.examples/build/pom.xml
Fixes #194
Tests with Java 5 failed due to artifact doxia-site-renderer-1.7.4 compiled for Java 6 (from maven-reporting-impl:jar:3.0.0) - blocked by #314
=> Require at least Maven 3.0 for jacoco-maven-plugin

jacoco-maven-plugin/src/org/jacoco/maven/AbstractAgentMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/AbstractJacocoMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/CheckMojo.java, jacoco-maven-plugin/src/org/jacoco/maven/InstrumentMojo.java, org.jacoco.doc/docroot/doc/changes.html
=> Remove misleading parameters of jacoco-maven-plugin goals

org.jacoco.cli/pom.xml
Currently when Maven uses
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```
execution of
```
mvn clean package -Djdk.version=10 -Dbytecode.version=10
```
fails
```
...
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ org.jacoco.cli ---
[INFO] Toolchain in maven-compiler-plugin: JDK[/Users/evgeny.mandrikov/.java-select/versions/10]
...
[INFO] --- exec-maven-plugin:1.5.0:java (default) @ org.jacoco.cli ---
[WARNING]
java.lang.UnsupportedClassVersionError: org/jacoco/cli/internal/XmlDocumentation has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at …
```
=> Configure exec-maven-plugin to use selected JDK toolchain 

jacoco-maven-plugin/src/org/jacoco/maven/ReportSupport.java, org.jacoco.ant/src/org/jacoco/ant/ReportTask.java, org.jacoco.core.test/src/org/jacoco/core/analysis/CoverageBuilderTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/ClassCoverageImplTest.java, org.jacoco.core/src/org/jacoco/core/analysis/CoverageBuilder.java, org.jacoco.core/src/org/jacoco/core/analysis/CoverageNodeImpl.java, org.jacoco.core/src/org/jacoco/core/analysis/ICoverageNode.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassAnalyzer.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassCoverageImpl.java, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/ReportStructureTestDriver.java, org.jacoco.report.test/src/org/jacoco/report/csv/CSVFormatterTest.java, org.jacoco.report.test/src/org/jacoco/report/csv/CSVGroupHandlerTest.java, org.jacoco.report.test/src/org/jacoco/report/html/HTMLFormatterTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/BundlePageTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/PackagePageTest.java, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/PackageSourcePageTest.java, org.jacoco.report.test/src/org/jacoco/report/xml/XMLFormatterTest.java, org.jacoco.report/src/org/jacoco/report/csv/CSVGroupHandler.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/BundlePage.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/PackagePage.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/PackageSourcePage.java
Fixes #806
Our own XML report before this change is 915700 bytes, after is 920811 - increase is just 0.6%.
=> Preserve empty class and sourcefile nodes in XML report

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/html/page/BundlePageTest.java, org.jacoco.report/src/org/jacoco/report/internal/html/page/BundlePage.java
Using Ant Task and therefore Gradle Plugin, that is based on it, possible to generate report without classes.
For example in case of following `build.xml`
```
<project xmlns:jacoco="antlib:org.jacoco.ant" default="build">
<taskdef uri="antlib:org.jacoco.ant" resource="org/jacoco/ant/antlib.xml">
<classpath path="jacoco/lib/jacocoant.jar"/>
</taskdef>
<target name="build">
<jacoco:report>
<structure name="example"/>
<html destdir="report"/>
</jacoco:report>
</target>
</project>
```
and `build.gradle`
```
apply plugin: 'base'
apply plugin: 'jacoco'
repositories {
mavenCentral()
mavenLocal()
}
task report(type:JacocoReport) {
executionData.from(files(file('jacoco.exec')))
}
```
execution of
```
$ ant
Buildfile: /private/tmp/example/build.xml
build:
[jacoco:report] Writing bundle 'example' …
```
=> Replace empty table in HTML report by messages

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilter.java, org.jacoco.doc/docroot/doc/changes.html
During attempt to test resolution of [KT-28453](https://youtrack.jetbrains.com/issue/KT-28453) (#791) in Kotlin 1.3.30 EAP
```diff
--- a/org.jacoco.core.test.validation.kotlin/pom.xml
+++ b/org.jacoco.core.test.validation.kotlin/pom.xml
@@ -28,2 +28,2 @@
-    <kotlin.version>1.3.0</kotlin.version>
+    <kotlin.version>1.3.30-eap-11</kotlin.version>
</properties>
@@ -47,3 +47,16 @@
</dependencies>
+  <repositories>
+    <repository>
+      <id>kotlin-eap</id>
+      <url>https://dl.bintray.com/kotlin/kotlin-eap</url>
+    </repository>
+  </repositories>
+  <pluginRepositories>
+    <pluginRepository>
+      <id>kotlin-eap</id>
+      <url>https://dl.bintray.com/kotlin/kotlin-eap</url>
+    </pluginRepository>
+  </pluginRepositories>
+
<build>
```
Thanks to our validation tests I …
=> Update KotlinCoroutineFilter for Kotlin 1.3.30

org.jacoco.core.test/src/org/jacoco/core/test/perf/ExecuteInstrumentedCodeScenario.java, org.jacoco.core.test/src/org/jacoco/core/test/perf/InstrumentationSizeSzenario.java, org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.doc/docroot/doc/changes.html
There are several problems with methods [`Instrumenter.instrument(ClassReader)`](https://github.com/jacoco/jacoco/blob/v0.8.3/org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java#L72-L82) and [`Analyzer.analyzeClass(ClassReader)`](https://github.com/jacoco/jacoco/blob/v0.8.3/org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java#L104-L112) :
* their implementations use
[field `org.objectweb.asm.ClassReader.b` which was marked as deprecated in ASM 7.1](https://gitlab.ow2.org/asm/asm/commit/5ed1a4abbbbd4ba416a5f3d99031535e89a2e88f)
* they don't work in case when field `ClassReader.b` contains more than just bytes of one class (see [`ClassReader(byte[] classFileBuffer, int classFileOffset, int classFileLength)`](https://gitlab.ow2.org/asm/asm/blob/ASM_7_1/asm/src/main/java/org/obje …
=> Remove `instrument(ClassReader)` and `analyzeClass(ClassReader)`

org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/InstrumentTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/ClassFileVersionsTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/CondyProbeArrayStrategyTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactoryTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/CondyProbeArrayStrategy.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactory.java, org.jacoco.doc/docroot/doc/changes.html
Users often forget to ignore **synthetic** fields when using reflection and continue asking questions even if this is already described in [our FAQ](https://github.com/jacoco/jacoco/blob/v0.8.3/org.jacoco.doc/docroot/doc/faq.html#L130-L141) - here is some recent ones:
* #834
* #816
* #799
* https://groups.google.com/d/msg/jacoco/3wT1WmrRPBA/A9MPMa6tHAAJ
We can get rid of this field in Java 11+ class files by using condy ([JEP 309](https://openjdk.java.net/jeps/309)).
Also I think that condy might be better in terms of performance than `ClassFieldProbeArrayStrategy` in following cases
* cold non JITed code and I suppose that this is quite common case when running unit tests
* when JIT fails to inline `$jacocoInit`
=> Use condy for probes array in Java 11+ class files

org.jacoco.build/pom.xml, org.jacoco.core.test/src/org/jacoco/core/internal/instr/InstrSupportTest.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactory.java, org.jacoco.doc/docroot/doc/changes.html
=> Upgrade ASM to 7.1

org.jacoco.core.test/src/org/jacoco/core/internal/instr/InstrSupportTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java
In follow-up to https://github.com/jacoco/jacoco/pull/851#issuecomment-470745829
=> Method `needsFrames` should also consider high byte of version

org.jacoco.core.test/src/org/jacoco/core/test/InstrumentingLoader.java, org.jacoco.core.test/src/org/jacoco/core/test/InstrumentingLoaderTest.java
Because execution of `java.lang.ClassLoader.defineClass` multiple
times with same class name causes `java.lang.LinkageError` with
message "duplicate class definition".
=> InstrumentingLoader should use findLoadedClass

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinInlineTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinDefaultArgumentsTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilterTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilter.java, org.jacoco.doc/docroot/doc/changes.html
For open functions with default arguments
```
open class Open {
open fun f(a: String = "a") {
}
}
```
Kotlin compiler generates check that default arguments are not used for super calls - https://github.com/JetBrains/kotlin/blob/v1.3.31/compiler/backend/src/org/jetbrains/kotlin/codegen/FunctionCodegen.java#L1341-L1359 , even if currently such calls not allowed - compiler rejects following
```
class Derived : Open() {
override fun f(a: String) {
super.f() // Error: Super-calls with default arguments are not allowed. Please specify all arguments of 'super.f' explicitly
}
}
```
I suppose that check is introduced for future versions of language, where such calls might be allowed.
This PR adds handling of open functions to `KotlinDefaultArgumentsFilter`.
Fixes #882
=> Filter unreachable branches in Kotlin open functions with default arguments

org.jacoco.core/src/org/jacoco/core/internal/analysis/Instruction.java, org.jacoco.doc/javadoc/overview.html
In JDK 13 EA b13 validation of headers in javadocs become stricter:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project org.jacoco.core: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /Users/evgeny.mandrikov/projects/jacoco/org.jacoco.core/src/org/jacoco/core/internal/analysis/Instruction.java:26: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
[ERROR]  * <h3>Step 1: Building the CFG</h3>
[ERROR]    ^
```
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project org.jacoco.doc: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - …
```
=> Fix headers in javadocs

org.jacoco.report.test/src/org/jacoco/report/internal/html/table/BarColumnTest.java
This change restores ability to build JaCoCo using JDK 13 EA >= b21.
=> Fix test for JDK 13 EA >= b21

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinDefaultArgumentsTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilterTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/SyntheticFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/SyntheticFilter.java, org.jacoco.doc/docroot/doc/changes.html
Similarly to #773 constructors in Kotlin can have default arguments with branches, what unfortunately was overlooked during implementation of #774 - currently we filter them out, because they gets compiled differently than functions:
```
class Example() {
constructor(a: Boolean, b: String = if (a) "a" else "b") : this()
}
```
results in constructor with following signature
```
public synthetic <init>(ZLjava/lang/String;ILkotlin/jvm/internal/DefaultConstructorMarker;)V
```
This was discovered during implementation of #887.
=> Do not filter out synthetic constructors that contain values of default arguments in Kotlin

org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeInserterTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeInserter.java, org.jacoco.doc/docroot/doc/changes.html
Using
```
$ javac -version
javac 11.0.3
```
compilation (`javac -g Example.java`) of
```
@java.lang.annotation.Documented
@java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.CLASS)
@java.lang.annotation.Target(java.lang.annotation.ElementType.TYPE_USE)
@interface NonNull {
}
class Example {
Object legacy() {
return null;
}
Object example() {
@NonNull Object o = legacy();
return o;
}
}
```
results (`javap -v -p Example.class`) in
```
java.lang.Object example();
descriptor: ()Ljava/lang/Object;
flags: (0x0000)
Code:
stack=1, locals=2, args_size=1
0: aload_0
1: invokevirtual #2                  // Method legacy:()Ljava/lang/Object;
4: astore_1
5: aload_1
6: areturn
LineNumberTable:
line 13: 0
line 14: 5
LocalVariableTable:
Start  Length  Slot  Name   Signature
0       7 …
```
=> ProbeInserter should update indexes of local variables in annotations

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinDefaultArgumentsTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> KotlinDefaultArgumentsFilter should not assume that all parameters consume one slot

org.jacoco.build/pom.xml
Because import of the former is deprecated.
=> Replace import of JaCoCo "exec" file into SonarQube by import of XML

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/DirectorySourceFileLocatorTest.java, org.jacoco.report/src/org/jacoco/report/DirectorySourceFileLocator.java
A corner case has been reported where the source reference points to an folder. Instead of ignoring such a reference (as we do for missing files) in this case the report generation process fails. This fix checks that the source reference actually points to a file.
The issue war reported on the mailing list: https://groups.google.com/forum/?fromgroups=#!topic/jacoco/cx9sTR3KMr4
=> Check whether source reference actually is a file

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinWhenStringFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinWhenStringFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> Fix NPE in KotlinWhenStringFilter

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/StringSwitchEcjFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/StringSwitchEcjFilter.java, org.jacoco.doc/docroot/doc/changes.html
Following bytecode
```
0: aload_1
1: astore_2
2: invokevirtual #121                // Method java/lang/String.hashCode:()I
5: lookupswitch  { // 0
default: 17
}
17:
```
will cause NPE in `StringSwitchEcjFilter`.
=> Fix NPE in StringSwitchEcjFilter

jacoco-maven-plugin/src/org/jacoco/maven/InstrumentMojo.java, org.jacoco.doc/docroot/doc/faq.html
Case of offline instrumentation was forgotten in https://github.com/jacoco/jacoco/pull/932 while causes similar questions - https://stackoverflow.com/questions/58189496/jacoco-offline-instrumentation-in-goalinstrument-goal-analyzes-the-entire
=> Update documentation about "excludes" option of offline instrumentation

org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/ContentTypeDetectorTest.java, org.jacoco.core/src/org/jacoco/core/internal/ContentTypeDetector.java, org.jacoco.doc/docroot/doc/changes.html
Each time new version of bytecode comes out, we have following inconsistency between processing of classes by agent and processing of files:
offline instrumentation and report generation skip class file
```
$ cat <<END > Example.java
class Example {
public static void main(String[] args) {
}
END
$ javac --release 14 Example.java -d classes
$ ls classes
Example.class
$ java -jar jacoco-0.8.3/lib/jacococli.jar instrument classes --dest instrumented
[INFO] 0 classes instrumented to /tmp/j/instrumented.
$  java -jar jacoco-0.8.3/lib/jacococli.jar report --classfiles classes
[WARN] No execution data files provided.
[INFO] Analyzing 0 classes.
```
which is IMO misleading and error-prone,
whereas on-the-fly instrumentation fails
```
$ java -javaagent:jacoco-0.8.3/lib/jacocoagent.jar -cp classes …
```
=> ContentTypeDetector should recognize future versions of Java class files

.gitattributes, org.jacoco.build/pom.xml
@marchof thanks to your explanation ❤️ in https://github.com/jacoco/jacoco/pull/954 
> A couple of years ago the Eclipse formatter was reworked.
I  finally understood why Eclipse Code Formatter in IntelliJ at some moment in time started to change formatting when applied on old code. And why [Spotless](https://github.com/diffplug/spotless) was doing the same during my previous attempt to use it for checking of formatting during build.
Given that after https://github.com/jacoco/jacoco/pull/955 formatting will be completely consistent, I propose to add check into build. This will also allow contributors to easily fix formatting even without proper IDE setup - following message is printed when check fails: `Run 'mvn spotless:apply' to fix these violations.` 🎉
=> Check code formatting during build

org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/ContentTypeDetectorTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/Pack200StreamsTest.java, org.jacoco.core/src/org/jacoco/core/internal/Pack200Streams.java, org.jacoco.doc/docroot/doc/changes.html
Pack200 was deprecated in JDK 13 (https://openjdk.java.net/jeps/336)
with planned removal in JDK 14 (https://openjdk.java.net/jeps/367)
which happened recently (http://hg.openjdk.java.net/jdk/jdk/rev/f236fd5d0c2c)
and supposed to be part of upcoming [JDK 14 Early Access](http://jdk.java.net/14/)  Build 27.
This doesn't cause troubles with released JaCoCo 0.8.5 for cases without processing of Pack200, and in the last case it fails as following
```
$ java -jar jacoco-0.8.5/lib/jacococli.jar classinfo org.eclipse.eclemma.core_3.1.2.201903112331.jar.pack.gz
INST   BRAN   LINE   METH   CXTY   ELEMENT
Exception in thread "main" java.lang.NoClassDefFoundError: java/util/jar/Pack200
at org.jacoco.cli.internal.core.internal.Pack200Streams.unpack(Pack200Streams.java:43)
at …
```
=> Absence of Pack200 in JDK 14 should not cause failure of JaCoCo build

org.jacoco.doc/docroot/doc/build.html
Because last one pollutes local Maven repository.
=> Documentation should advise usage of "mvn verify" instead of "mvn install"

org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.doc/docroot/doc/changes.html
=> Preserve compression method when instrumenting zip entries

jacoco-maven-plugin.test/it/it-report-nomatch/verify.bsh, jacoco-maven-plugin/src/org/jacoco/maven/ReportSupport.java, org.jacoco.ant.test/src/org/jacoco/ant/ReportTaskTest.xml, org.jacoco.ant/src/org/jacoco/ant/ReportTask.java
change language from "..do no match with execution data" to "..do not
match with execution data.
This is a simple change in grammer both to the code and the tests.
It can be seen when the classes that jacoco is looking at do not match the classes that were used by the tests.
=> improve english grammer

org.jacoco.build/licenses/asm-9.0.html, org.jacoco.build/pom.xml, org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/ClassFileVersionsTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/InstrSupportTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java, org.jacoco.doc/docroot/doc/changes.html
Also use ASM for Java 16 class files directly.
=> Upgrade to ASM 9.0

org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java, org.jacoco.doc/docroot/doc/changes.html
For following `Example.java`
```
sealed class Shape
permits Circle
{
}
final class Circle extends Shape {
}
```
compiled as
```
javac --enable-preview --release 15 -d classes Example.java
```
by
```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment (build 15+36-1562)
OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)
```
Execution of
```
java -jar jacococli.jar instrument classes --dest instrumented
```
succeeds when using released JaCoCo 0.8.6,
however fails when using snapshot after https://github.com/jacoco/jacoco/pull/1094
```
Exception in thread "main" java.io.IOException: Error while instrumenting /private/tmp/j/classes/Shape.class.
at org.jacoco.cli.internal.core.instr.Instrumenter.instrumentError(Instrumenter.java:160)
at …
```
=> Use ASM9 API

org.jacoco.doc/xsl/junit-noframes.xsl
While reviewing #1091 I discovered that we show an always empty column in the JUnit test report.
=> Remove empty timestamp column in test report

org.jacoco.core.test.validation.groovy/pom.xml, org.jacoco.core.test.validation/pom.xml, org.jacoco.doc/docroot/doc/build.html
Since GMavenPlus 1.9.0 Java 14 and Java 15 is supported. This version of
GMavenPlus requires Groovy 3.x, so also update Groovy to latest version.
For other JVM languages I propose that we focus on the last stable
release, so Groovy 3.x should be ok as a test target.
As Java 7 is not supported any more therefore Groovy tests are now
executed for >= Java 8
This closes #1022 being a rebased/updated version of it.
=> Upgrade Groovy to 3.0.6 to support latest Java versions

jacoco-maven-plugin/src/org/jacoco/maven/ReportSupport.java
Fix bundleName mispelling in ReportSupport (was bundeName)
=> Fix bundleName typo in ReportSupport

org.jacoco.examples.test/src/test/resources/verify-it.bsh, org.jacoco.examples.test/src/test/resources/verify-offline.bsh, org.jacoco.examples.test/src/test/resources/verify.bsh
This fixes build with JDKs from 9 to 16 EA b27 with
`MAVEN_OPTS=--illegal-access=deny`
and with JDK 16 EA b28, where `--illegal-access=deny`
is default due to integration of JEP 396.
=> Use BeanShell instead of Groovy scripts

org.jacoco.core.test.validation.scala/pom.xml
This is the latest version from Scala 2.12 series.
=> Upgrading Scala validation tests to Scala 2.13.4

org.jacoco.cli.test/src/org/jacoco/cli/internal/commands/DumpTest.java
For a non-English system the error message may differ.
E.g. on a Hungarian system it says:
"[WARN] Kapcsolat elutasítva (Connection refused)."
This fails the test as it does not include "[WARN] Connection refused".
Change the assert to allow for the changed error message.
=> Change assert for CLI DumpTest to pass on non-English systems

org.jacoco.core.test.validation.kotlin/pom.xml, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinUnsafeCastOperatorFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinUnsafeCastOperatorFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> Update filter for unsafe cast operator for Kotlin 1.4

org.jacoco.core.test.validation.kotlin/pom.xml, org.jacoco.core.test.validation/pom.xml, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> Update filter for suspending lambdas for Kotlin 1.4.20

org.jacoco.core.test.validation/pom.xml
Scala 2.12 should work also on Java 11 and 12.
https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
=> Enabling Scala tests for new bytecode profiles

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/SyntheticFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/SyntheticFilter.java, org.jacoco.doc/docroot/doc/changes.html
Currently execution of
```
mvn clean package -Dkotlin.version=1.5.0-M2
```
leads to
```
Failed tests:
all_missed_instructions_should_have_line_number(org.jacoco.core.test.validation.kotlin.KotlinCoroutineTest): sum of missed instructions of all lines should be equal to missed instructions of file expected:<4> but was:<2>
```
---
For the following `Example.kt`
```
private suspend fun example() {
println("private")
}
```
Execution of
```
kotlin/bin/kotlinc Example.kt -d classes
javap -v -p classes/ExampleKt.class
```
using Kotlin compiler version `1.4` produces
```
{
static final java.lang.Object example(kotlin.coroutines.Continuation<? super kotlin.Unit>);
descriptor: (Lkotlin/coroutines/Continuation;)Ljava/lang/Object;
flags: (0x1018) ACC_STATIC, ACC_FINAL, ACC_SYNTHETIC
Code:
stack=2, …
```
=> Update filter for Kotlin 1.5 suspending functions

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinControlStructuresTarget.kt
Currently execution of any of
```
mvn clean package -Dkotlin.version=1.5.0-M1
mvn clean package -Dkotlin.version=1.5.0-M2
mvn clean package -Dkotlin.version=1.5.0-RC
mvn clean package -Dkotlin.version=1.5.0
```
leads to
```
Failed tests:
execute_assertions_in_comments(org.jacoco.core.test.validation.kotlin.KotlinControlStructuresTest): Instructions (KotlinControlStructuresTarget.kt:67) expected:<[PART]LY_COVERED> but was:<[FUL]LY_COVERED>
```
---
For the following Example.kt
```
fun example() {
for (i in 0..-1) {
nop()
}
}
fun nop() {
}
```
Execution of
```
kotlin/bin/kotlinc Example.kt -d classes
javap -v -p classes/ExampleKt.class
```
using Kotlin compiler version 1.4 produces
```
public static final void example();
descriptor: ()V
flags: ACC_PUBLIC, ACC_STATIC, ACC_FINAL
Code:
stack=2, …
```
=> Update KotlinControlStructuresTarget for Kotlin 1.5

org.jacoco.core.test.validation.java16/.classpath, org.jacoco.core.test.validation.java16/.project, org.jacoco.core.test.validation.java16/pom.xml, org.jacoco.core.test.validation.java16/src/org/jacoco/core/test/validation/java16/InstanceofTest.java, org.jacoco.core.test.validation.java16/src/org/jacoco/core/test/validation/java16/RecordsTest.java, org.jacoco.core.test.validation.java16/src/org/jacoco/core/test/validation/java16/targets/InstanceofTarget.java, org.jacoco.core.test.validation.java16/src/org/jacoco/core/test/validation/java16/targets/RecordsTarget.java, org.jacoco.core.test.validation/pom.xml, org.jacoco.doc/docroot/doc/build.html
Also remove preview features from Java 14 validation tests.
=> Add module for Java 16 validation tests

jacoco-maven-plugin/pom.xml
=> Use `provided` scope for `maven-core` and `maven-plugin-api` dependencies

.azure-pipelines/azure-pipelines.yml
Seems that Maven 3.8.2 contains bug, which prevents us from using it.
=> Use Maven 3.8.1 in Azure Pipelines

org.jacoco.doc/docroot/doc/faq.html
A sequence of instructions between two probes may correspond to several lines.
In that case, as identified in #1223, an exception may "hide" the executed status of several lines, and not just one.
=> Fix misleading FAQ

.azure-pipelines/azure-pipelines.yml, org.jacoco.build/pom.xml
Maven 3.8.1 disappeared from https://downloads.apache.org/maven/maven-3/ which causes our builds in Azure Pipelines to fail - see for example [build](https://dev.azure.com/jacoco-org/JaCoCo/_build/results?buildId=531&view=results) after merge of #1226
Instead we should be downloading from https://archive.apache.org/dist/maven/maven-3/ that contains all released versions.
Also seems that recently released Maven 3.8.3 solves the issue that we encountered with 3.8.2
Unfortunately Azure Pipelines images was not yet updated and still come with preinstalled Maven 3.8.2
Fixes #1218
=> Use Maven 3.8.3 in Azure Pipelines

org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeInserterTest.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ProbeInserter.java, org.jacoco.doc/docroot/doc/changes.html
By inserting the probe array access code at the beginning of the method
we accidently moved the range of the debug symbols of the method
parameters after the probe array access code. Actually the method
parameters are still valid from the very beginning of the method.
This offset in the method parameter's debug symbols may confuse tools
like Jandex.
=> Fix range for debug symbols of method parameters

org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/CoverageTransformerTest.java, org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/ExceptionRecorder.java, org.jacoco.core.test/src/org/jacoco/core/JaCoCoTest.java, org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java, org.jacoco.core/src/org/jacoco/core/JaCoCo.java, org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.core/src/org/jacoco/core/jacoco.properties, org.jacoco.doc/docroot/doc/changes.html
This should help in situations where users cannot see which version is actually used, like in AGP builds.
=> Include JaCoCo version in instrumentation/analysis exception messages

org.jacoco.build/pom.xml
Since version 9.3 ASM provide a Bill Of Materials (BOM). So we can remove a few lines from our dependency management.
=> Use ASM Bill Of Materials (BOM)

org.jacoco.build/pom.xml
Starting from version 2.11 maven-surefire-plugin does not ignore
a failure to start forked JVM and causes build failure,
e.g. if there is an exception during JaCoCo agent startup
(https://issues.apache.org/jira/browse/SUREFIRE-780)
While implementing #1334 I was tricked multiple times by the absence of build failure.
Fixes #828
=> Upgrade maven-surefire-plugin to 2.19.1

.azure-pipelines/azure-pipelines.yml, org.jacoco.build/pom.xml
In my opinion convenient to refer to Java `1.5` as `5`, but unfortunately `maven-compiler-plugin` version `3.7.0` doesn't agree and execution of JaCoCo build as
```
mvn package -Dbytecode.version=5
```
leads to
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project org.jacoco.core: Compilation failure
javac: invalid flag: -s
```
=> Upgrade maven-compiler-plugin to 3.10.1

jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java
Follow-up to https://github.com/jacoco/jacoco/pull/1007. The new `includeCurrentProject` that has yet to be released is listed in the documentation as available since release 0.7.7.
=> Document `includeCurrentProject` available as of 0.8.9

jacoco-maven-plugin.test/it/setup-parent/pom.xml, jacoco-maven-plugin.test/pom.xml, org.jacoco.examples.test/pom.xml
`org.jacoco.examples.test` and `jacoco-maven-plugin.test` use `maven-invoker-plugin`,
[which by default for forked Maven invocations uses the same JDK that is used for Maven](https://maven.apache.org/plugins/maven-invoker-plugin/run-mojo.html#javaHome).
So the execution of the build with JDK >= 9 for Maven and JDK 5 for compilation
```
mvn clean verify -Djdk.version=5 -Dbytecode.version=5
```
currently leads to failure
```
[INFO] --- maven-invoker-plugin:2.0.0:run (test-pom) @ org.jacoco.examples.test ---
[INFO] Building: build/pom.xml
[INFO] ..FAILED (1.4 s)
[INFO]   The build exited with code 1. See /Users/godin/projects/jacoco/jacoco/org.jacoco.examples.test/target/it/build/build.log for details.
```
`org.jacoco.examples.test/target/it/build/build.log`
```
[ERROR] COMPILATION ERROR : …
```
=> Support targeting JDK 5 when using JDK >= 9 for Maven

.azure-pipelines/azure-pipelines.yml
AzurePipelines currently shows the following warning
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
[Ubuntu 18.04 in AzurePipelines by default uses Java 8](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu1804-Readme.md#java), whereas [Ubuntu 20.04 uses Java 11](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java), so this requires https://github.com/jacoco/jacoco/pull/1398 in order to not switch away from the default.
=> Use Ubuntu 20.04 in AzurePipelines

org.jacoco.core.test.validation.java20/.classpath, org.jacoco.core.test.validation.java20/.project, org.jacoco.core.test.validation.java20/pom.xml, org.jacoco.core.test.validation.java20/src/org/jacoco/core/test/validation/java20/SwitchPatternMatchingTest.java, org.jacoco.core.test.validation.java20/src/org/jacoco/core/test/validation/java20/targets/SwitchPatternMatchingTarget.java, org.jacoco.core.test.validation/pom.xml
This requires OpenJDK 17 Early Access build with https://github.com/openjdk/jdk/pull/3863
=> Add validation test for JEP 433: Pattern Matching for switch

.azure-pipelines/azure-pipelines.yml, org.jacoco.build/pom.xml, org.jacoco.core.test.validation.java14/src/org/jacoco/core/test/validation/java14/SwitchExpressionsTest.java, org.jacoco.core.test.validation.java14/src/org/jacoco/core/test/validation/java14/targets/SwitchExpressionsTarget.java, org.jacoco.core.test.validation.java16/src/org/jacoco/core/test/validation/java16/InstanceofTest.java, org.jacoco.core.test.validation.java16/src/org/jacoco/core/test/validation/java16/targets/InstanceofTarget.java, org.jacoco.doc/docroot/doc/build.html
Version `4.6.1` of previously used artifact `org.eclipse.jdt:ecj` was actually version of Eclipse IDE.
This version supports source/target from Java 1.1 up to 19.
Also note that starting from version `3.27.0` ECJ requires Java 11 for execution.
=> Upgrade ECJ from 3.12.1 to 3.32.0

org.jacoco.core.test.validation.java20/src/org/jacoco/core/test/validation/java20/RecordPatternsTest.java, org.jacoco.core.test.validation.java20/src/org/jacoco/core/test/validation/java20/targets/RecordPatternsTarget.java
OpenJDK 21 EA b15 and b16 produce different class files for `RecordPatternsTarget.java` because of
https://github.com/openjdk/jdk/commit/138cdc9283ae8f3367e51f0fe7e27833118dd7cb
Here is diff between outputs of `javap -v -p RecordPatternsTarget.class`:
```diff
line 34: 57
line 35: 72
+         line 34: 78
line 37: 92
```
Bytecode instructions at offset 78 correspond to the following exception handler generated for the `case` at line 34:
```
78: astore_1
79: new           #24                 // class java/lang/MatchException
82: dup
83: aload_1
84: invokevirtual #26                 // Method java/lang/Throwable.toString:()Ljava/lang/String;
87: aload_1
88: invokespecial #30                 // Method java/lang/MatchException."<init>":(Ljava/lang/String;Ljava/lang/Throwable;)V
91: athrow
```
=> Fix validation test for Java 21

org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/AgentModuleTest.java, org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/AgentModule.java, org.jacoco.ant.test/src/org/jacoco/ant/CoverageTaskTest.xml, org.jacoco.ant.test/src/org/jacoco/ant/data/policy.txt, org.jacoco.doc/docroot/doc/changes.html
Execution of
```
java \
-Djava.security.manager -Djava.security.policy==policy.txt -Djava.security.debug=access,failure \
-javaagent:jacocoagent.jar=output=none \
-version
```
using the following `policy.txt`
```
grant codeBase "file:${user.dir}/jacocoagent.jar" {
permission java.security.AllPermission;
};
```
and JaCoCo agent version `0.8.8` leads to
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
```
Whereas using JaCoCo agent version `0.8.9` leads to
```
access: access denied ("java.io.FilePermission" "/private/tmp/jacoco/jacocoagent.jar" "read")
java.lang.Exception: Stack trace
at java.base/java.lang.Thread.dumpStack(Thread.java:1387)
at …
```
=> AgentModule should set ProtectionDomain when defining classes

org.jacoco.build/pom.xml, org.jacoco.core/src/org/jacoco/core/jacoco.properties, org.jacoco.doc/docroot/index.html
Prior to this change execution of some tests in IntelliJ IDEA 2022.3.3 fails with `ExceptionInInitializerError`
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 7
at java.lang.String.substring(String.java:1963)
at org.jacoco.core.JaCoCo.<clinit>(JaCoCo.java:44)
```
because build of the project in IntelliJ IDEA produces following `org.jacoco.core/target/classes/org/jacoco/core/jacoco.properties`
```
VERSION=${qualified.bundle.version}
COMMITID=
HOMEURL=http://www.jacoco.org/jacoco
RUNTIMEPACKAGE=${jacoco.runtime.package.name}
```
after this change produces
```
VERSION=${qualified.bundle.version}
COMMITID=0000000
HOMEURL=http://www.jacoco.org/jacoco
RUNTIMEPACKAGE=${jacoco.runtime.package.name}
```
and tests pass.
=> Fix execution of tests in IntelliJ IDEA

org.jacoco.build/pom.xml
This reduces number of warnings produced by Maven 3.9.2
```
[INFO] Total time:  02:00 min
[INFO] Finished at: 2023-05-15T10:26:59+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 24 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:2.4.1
[WARNING]  * org.apache.maven.plugins:maven-javadoc-plugin:3.0.1
[WARNING]  * …
```
=> Upgrade exec-maven-plugin to 3.1.0

org.jacoco.build/pom.xml
Unfortunately #1437 broke build from terminal.
After 4dc8b3855c82c868d7756944519c90d4326913da build from terminal and in CI produces following
`org.jacoco.core/target/classes/org/jacoco/core/jacoco.properties`
```
VERSION=0.8.11.202305151209
COMMITID=0000000
HOMEURL=http://www.jacoco.org/jacoco
RUNTIMEPACKAGE=org.jacoco.agent.rt.internal_0000000
```
https://www.jacoco.org/jacoco/trunk/index.html currently shows
> This is the distribution of version 0.8.11.202305120500 created on 2023/05/12 based on commit 0000000.
Fortunately we have a check that activates at release time and is able to detect this - `mvn clean verify -Prelease` fails as following
```
[WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireProperty failed with message:
Property "build.commitId" evaluates to "0000000". …
```
=> Fix computation of `build.commitId`

org.jacoco.build/pom.xml
This reduces number of warnings produced by Maven 3.9.2
```
[INFO] Total time:  02:00 min
[INFO] Finished at: 2023-05-15T10:26:59+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 24 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:2.4.1
[WARNING]  * org.apache.maven.plugins:maven-javadoc-plugin:3.0.1
[WARNING]  * …
```
=> Upgrade maven-compiler-plugin to 3.11.0

org.jacoco.build/pom.xml
This reduces number of warnings produced by Maven 3.9.2 - prior to this change on 2768531ef72e04bc08c221295ad88d564037e81e:
```
[INFO] Total time:  53.242 s
[INFO] Finished at: 2023-05-16T23:45:03+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 22 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-plugin-plugin:3.6.0
[WARNING]  * org.jacoco:jacoco-maven-plugin:0.8.11-SNAPSHOT
[WARNING]  * com.github.genthaler:beanshell-maven-plugin:1.4
[WARNING]  * …
```
=> Upgrade maven-enforcer-plugin to 3.3.0

org.jacoco.build/pom.xml
```
[INFO] Total time:  58.035 s
[INFO] Finished at: 2023-05-17T00:15:23+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 21 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-plugin-plugin:3.6.0
[WARNING]  * org.jacoco:jacoco-maven-plugin:0.8.11-SNAPSHOT
[WARNING]  * com.github.genthaler:beanshell-maven-plugin:1.4
[WARNING] …
```
=> Upgrade build-helper-maven-plugin to 3.4.0

org.jacoco.build/pom.xml
This reduces number of warnings produced by Maven 3.9.2 - prior to this change on 41dbbb01f659f14860cbd5bd6e5c3dbcdf95f0dc:
```
...
[INFO] Total time:  58.035 s
[INFO] Finished at: 2023-05-17T00:15:23+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 19 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-source-plugin:2.1.2
...
```
Note that the new version produces slightly different `source.jar` files - below is an example of `org.jacoco.core-0.8.11-SNAPSHOT-sources.jar`, others in the same way:
adds entries `META-INF/maven/org.jacoco/org.jacoco.core/pom.xml`
and …
=> Upgrade maven-source-plugin to 3.2.1

org.jacoco.build/pom.xml, org.jacoco.core/src/org/jacoco/core/jacoco.properties
During the comparison of JAR files while doing #1444 I realized that unfortunately https://github.com/jacoco/jacoco/pull/1437 broke build from terminal and unfortunately https://github.com/jacoco/jacoco/pull/1443 did not fully fix it.
After https://github.com/jacoco/jacoco/commit/4dc8b3855c82c868d7756944519c90d4326913da and https://github.com/jacoco/jacoco/commit/740c51fd74934ea7549383984f21e8ffe3dc2910 build from terminal and in CI produces following `Eclipse-SourceReference` entry in `META-INF/MANIFEST.MF`
```
Eclipse-SourceReferences: scm:git:git://github.com/jacoco/jacoco.git;p
ath="org.jacoco.core";commitId=0000000
```
=> Fix generation of `Eclipse-SourceReference` entry in `MANIFEST.MF`

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  58.035 s
[INFO] Finished at: 2023-05-17T00:15:23+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 18 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-jar-plugin:2.3.1
...
```
Note that the new version produces slightly different `jar` files - `below is an example of org.jacoco.agent-0.8.11-SNAPSHOT.jar`, others in the same way:
`META-INF/MANIFEST.MF`
```diff
Manifest-Version: 1.0
-Archiver-Version: Plexus Archiver
Created-By: Apache Maven Bundle Plugin
-Built-By: godin …
```
=> Upgrade maven-jar-plugin to 3.3.0

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  58.035 s
[INFO] Finished at: 2023-05-17T00:15:23+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 17 plugin(s)
...
...
```
=> Upgrade maven-dependency-plugin to 3.5.0

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  42.077 s
[INFO] Finished at: 2023-05-22T11:42:01+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 18 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-plugin-plugin:3.6.0
[WARNING]  * org.jacoco:jacoco-maven-plugin:0.8.11-SNAPSHOT
[WARNING]  * com.github.genthaler:beanshell-maven-plugin:1.4
[WARNING]  * org.apache.maven.plugins:maven-shade-plugin:3.2.1
[WARNING] …
```
=> Upgrade maven-assembly-plugin to 3.6.0

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  42.077 s
[INFO] Finished at: 2023-05-22T11:42:01+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 17 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:2.5
...
```
=> Upgrade maven-resources-plugin to 3.3.1

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  42.077 s
[INFO] Finished at: 2023-05-22T11:42:01+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 16 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-antrun-plugin:1.6
...
```
=> Upgrade maven-antrun-plugin to 3.1.0

org.jacoco.core.test.validation.java20/src/org/jacoco/core/test/validation/java20/targets/RecordPatternsTarget.java
Quoting https://openjdk.org/jeps/440
> Apart from some minor editorial changes, the main change since the second preview is to remove support for record patterns appearing in the header of an enhanced for statement.
=> Update validation test in accordance with JEP 440

jacoco-maven-plugin/.classpath, jacoco-maven-plugin/pom.xml, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/maven.html
This change will
* unblock #1462 
* allow to solve #1435 differently than proposed in #1438
=> Require Java 8 for jacoco-maven-plugin

org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/build.html, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/environment.html
```
...
[INFO] Total time:  42.077 s
[INFO] Finished at: 2023-05-23T12:18:40+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 15 plugin(s)
...
[WARNING]  * org.codehaus.mojo:buildnumber-maven-plugin:1.2
...
```
Note that [`buildnumber-maven-plugin` starting from version `3.1.0` requires Maven `3.5.4`](https://github.com/mojohaus/buildnumber-maven-plugin/commit/d50551b6889b78a6901aeb4d419f3f0a17b8ff34) and thus transitively our build should require it too.
=> Upgrade buildnumber-maven-plugin to 3.1.0

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  37.693 s
[INFO] Finished at: 2023-05-24T23:18:14+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 14 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-dependency-plugin:3.5.0
...
```
=> Upgrade maven-dependency-plugin to 3.6.0

org.jacoco.build/pom.xml
```
...
[INFO] Total time:  02:20 min
[INFO] Finished at: 2023-05-24T23:38:33+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 13 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-source-plugin:3.2.1
...
```
=> Upgrade maven-source-plugin to 3.3.0

org.jacoco.core.test.validation.groovy/pom.xml
```
...
[INFO] Total time:  02:20 min
[INFO] Finished at: 2023-05-24T23:38:33+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 12 plugin(s)
...
[WARNING]  * org.codehaus.gmavenplus:gmavenplus-plugin:1.13.0
...
```
=> Upgrade gmavenplus-plugin to 3.0.0

org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
Initially in #1475 I wanted to add a validation test that verifies resolution of https://youtrack.jetbrains.com/issue/KT-35553 , but turns out that javac version `20` violates it on `RecordPatternsTarget` 😆 So decided to extract the addition of such test into dedicated PR.
=> Add test to catch cases when compilers generate wrong line numbers

org.jacoco.build/pom.xml
```
...
[WARNING] Plugin validation issues were detected in 10 plugin(s)
...
[WARNING]  * org.apache.maven.plugins:maven-shade-plugin:3.2.1
...
```
=> Upgrade maven-shade-plugin to 3.5.0

.appveyor.yml
* Nowadays AppVeyor sets `M2_HOME` pointing on preinstalled Maven, so the execution of downloaded `apache-maven-3.3.9\bin\mvn` actually leads to the execution of preinstalled.
* Also `mvn` uses `JAVA_HOME`, so its addition to `PATH` is not needed.
=> Remove unused parts of configuration for AppVeyor

org.jacoco.build/pom.xml
```
...
[WARNING] Plugin validation issues were detected in 9 plugin(s)
...
[WARNING]  * org.codehaus.mojo:xml-maven-plugin:1.0
...
```
=> Upgrade xml-maven-plugin to 1.1.0

.appveyor.yml, .azure-pipelines/azure-pipelines.yml, org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/build.html, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/environment.html
It requires Java 17 and thus transitively our build should require it too.
=> Upgrade ECJ to 3.34.0

org.jacoco.core.test/src/org/jacoco/core/internal/flow/LabelFlowAnalyzerTest.java, org.jacoco.core/src/org/jacoco/core/internal/flow/LabelFlowAnalyzer.java
See
* https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-6.html#jvms-6.5.ret
* https://asm.ow2.io/javadoc/org/objectweb/asm/MethodVisitor.html#visitVarInsn(int,int)
* https://gitlab.ow2.org/asm/asm/-/blob/ASM_9_5/asm/src/main/java/org/objectweb/asm/ClassReader.java?ref_type=tags#L2408-2409
=> `Opcodes.RET` should be processed by `visitVarInsn` instead of `visitInsn`

org.jacoco.core/src/org/jacoco/core/internal/flow/ClassProbesVisitor.java
Outdated since commit 72793f84314a393b86c5dc344499888b7113d20b in JaCoCo version 0.7.1
=> Fix misleading outdated javadoc

org.jacoco.build/licenses/asm-9.5.html, org.jacoco.doc/docroot/doc/api.html, org.jacoco.doc/docroot/doc/flow.html, org.jacoco.doc/docroot/doc/implementation.html
* http://asm.objectweb.org/ is broken outdated link
* in `META-INF/MANIFEST.MF` of ASM jars
* `Bundle-DocURL` points to http://asm.ow2.org/ - see https://gitlab.ow2.org/asm/asm/-/blob/ASM_9_5/build.gradle?ref_type=tags#L296
* `Bundle-License` points to https://asm.ow2.io/ - see https://gitlab.ow2.org/asm/asm/-/blob/ASM_9_5/build.gradle?ref_type=tags#L297
* in `pom.xml` of ASM
* `url` points to http://asm.ow2.io/ - see https://gitlab.ow2.org/asm/asm/-/blob/ASM_9_5/build.gradle?ref_type=tags#L390
* `license` `url` points to https://asm.ow2.io/ - see https://gitlab.ow2.org/asm/asm/-/blob/ASM_9_5/build.gradle?ref_type=tags#L387
* https://asm.ow2.org/ redirects to https://asm.ow2.io/
=> Fix links to ASM website

org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/BooleanExpressionsTarget.java
Validate Java language feature discussed in #1504.
=> Add validation tests for boolean expressions

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/flow/LabelFlowAnalyzerTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/ZeroLineNumberTest.java, org.jacoco.core/src/org/jacoco/core/internal/flow/LabelFlowAnalyzer.java, org.jacoco.doc/docroot/doc/changes.html
JaCoCo version `0.8.8`  was removing from `LineNumberTable` entries with zero line numbers (see stacktrace of `RuntimeException` and `classinfo` output below) due to a bug in ASM  (https://gitlab.ow2.org/asm/asm/-/issues/317989), this was fixed by an upgrade of ASM to `9.5` in JaCoCo version `0.8.9` (https://github.com/jacoco/jacoco/pull/1416), which unfortunately also lead to the insertion of more probes (see `execinfo` output below) and so broke exec-file compatibility (see `ArrayIndexOutOfBoundsException` and `IllegalStateException` below).
----
Using the following `Generator.java` which generates class file with zero line number for a method invocation instruction
```java
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor; …
```
=> Restore exec file compatibility after upgrade of ASM to version 9.5

org.jacoco.build/pom.xml
As recommended by https://maven.apache.org/pom.html#Licenses
=> Use SPDX identifier for license declaration in pom.xml

org.jacoco.doc/docroot/doc/integrations.html
Added a reference to the [JaCoCo extension for bld](https://github.com/rife2/bld-jacoco-report) to the `Integration Matrix` table
=> Added reference to the JaCoCo extension for bld

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinDefaultArgumentsTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> Fix KotlinDefaultArgumentsFilter for the case of more than 32 parameters

org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/FinallyTest.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
This is very handy for me when
* investigating failures of tests after compiler version update
* adding new tests
* updating existing tests
=> `execute_assertions_in_comments` should show all failed assertions instead of just first

.github/workflows/ci.yml, org.jacoco.doc/docroot/doc/environment.html
One of the advantages of GitHub Actions - they are easy to enable in forks on GitHub, which allows testing without publishing a branch in our repo and without opening PR.
So I propose to take a baby step and as a starter add this basic configuration for GitHub Actions. And later on will look at fully replacing AppVeyor and AzurePipelines.
=> Add configuration for GitHub Actions

.github/dependabot.yml
There were no announcements in ASM mailing list for the past two releases, so instead of wasting the time of @merks on this (see https://github.com/jacoco/jacoco/pull/1600#issuecomment-2017578336), I propose to use Dependabot.
=> Add configuration for Dependabot to simplify updates of ASM

.github/dependabot.yml
According to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#labels
> By default, Dependabot raises all pull requests with the `dependencies` label. If more than one package manager is defined, Dependabot includes an additional label on each pull request. This indicates which language or ecosystem the pull request will update, for example: `java`
This was overlooked in https://github.com/jacoco/jacoco/pull/1601
=> Configure labels that Dependabot assigns to PRs

org.jacoco.build/pom.xml, org.jacoco.core.test.validation.java7/pom.xml, org.jacoco.doc/docroot/doc/build.html
Due to https://bugs.openjdk.org/browse/JDK-8173605 currently the execution of build with JDK 20 and higher requires specification of `-Dbytecode.version`, ie execution of `mvn clean package -Dbytecode.version=8` succeeds, whereas execution of `mvn clean package` fails
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project org.jacoco.core: Compilation failure: Compilation failure:
[ERROR] Source option 7 is no longer supported. Use 8 or later.
[ERROR] Target option 7 is no longer supported. Use 8 or later.
```
=> Fix build with JDK >= 20 when option `-Dbytecode.version` is not provided

org.jacoco.core.test.validation.kotlin/pom.xml, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenExpressionTarget.kt, org.jacoco.core.test.validation/pom.xml, org.jacoco.doc/docroot/doc/build.html
=> Upgrade Kotlin to 1.9.23

org.jacoco.build/pom.xml
Prior to this change execution of
```
mvn clean verify -Djdk.version=23
```
using JDK 23 EA >= b16 fails with
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.3.0:enforce (enforce-distribution-size) on project jacoco:
[ERROR] Rule 0: org.apache.maven.enforcer.rules.files.RequireFilesSize failed with message:
[ERROR] /Users/evgeny.mandrikov/projects/jacoco/jacoco/jacoco/target/jacoco-0.8.13.202405130824.zip size (8253189) too large. Max. is 4600000/Users/evgeny.mandrikov/projects/jacoco/jacoco/jacoco/target/jacoco-0.8.13.202405130824.zip
```
due to https://bugs.openjdk.org/browse/JDK-8324774
After this change it will pass for JDK 23 EA >= b16, but unfortunately will fail for < b16 with
```
error: invalid flag: --no-fonts
```
=> Fix build of JaCoCo with JDK 23 EA after JDK-8324774

org.jacoco.build/pom.xml
Without this change execution of
```
mvn clean verify -Decj=false
```
causes the use of ECJ, which is IMO counterintuitive.
Only `-Decj=true` or `-Decj` or `-Pecj` should activate ECJ, but not `-Decj=false` nor `-Decj=foo`.
This was discovered while working on a migration from AzurePipelines to GitHub Actions.
In AzurePipelines we use `-Decj=true` to activate ECJ and `-Decj=` otherwise
https://github.com/jacoco/jacoco/blob/7589f79f3a7329b77c605a11a6825aed8b812f0f/.azure-pipelines/azure-pipelines.yml#L104
And interpretation of `-Decj=` is the same before and after this change.
Activation of profiles can be tested using
```
mvn -f org.jacoco.build --non-recursive help:active-profiles
```
See also https://maven.apache.org/guides/introduction/introduction-to-profiles.html#property
=> `mvn -Decj=false` should not activate the use of ECJ

org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/output/FileOutputTest.java
This was overlooked in aa16a7c25cfc119ba3486bb114d3d54dc1bcca6c
=> Add missing `Test` annotation to method in `FileOutputTest`

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinCrossinlineTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinCrossinlineTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java, org.jacoco.doc/docroot/doc/changes.html
=> Fix interpretation of Kotlin SMAP

org.jacoco.report/src/org/jacoco/report/internal/ReportOutputFolder.java
Incorrect since creation in commit 2f5a2fc86a1148674bd1d661111c621cfa912a6b in JaCoCo version 0.1.0
=> Fix javadoc

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilterTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinSMAPTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinSMAP.java
This decouples filtering logic from parsing, which is IMO good on its own.
And allows using parser for resolution of #654.
=> Extract SMAP parser from KotlinInlineFilter

org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/build.html, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/environment.html
Quoting https://maven.apache.org/docs/history.html
> Currently, plugins provide Maven API compatibility down to 3.2.5. New plugin releases will require Maven 3.6.3 or later.
And execution of
```
mvn versions:display-plugin-updates
```
shows
```
INFO] Require Maven 3.6.3 to use the following plugin updates:
[INFO]   maven-assembly-plugin .............................. 3.6.0 -> 3.7.1
[INFO]   maven-clean-plugin ................................. 3.2.0 -> 3.4.0
[INFO]   maven-compiler-plugin ............................ 3.11.0 -> 3.13.0
[INFO]   maven-dependency-plugin ............................ 3.6.0 -> 3.7.1
[INFO]   maven-deploy-plugin ................................ 3.1.1 -> 3.1.2
[INFO]   maven-enforcer-plugin .............................. 3.3.0 -> 3.5.0
[INFO]   maven-install-plugin …
```
=> Require at least Maven 3.6.3 for build

org.jacoco.doc/docroot/doc/changes.html, org.jacoco.report.test/src/org/jacoco/report/internal/NormalizedFileNamesTest.java, org.jacoco.report/src/org/jacoco/report/internal/NormalizedFileNames.java
Otherwise it changes file extensions.
Fixes #1656
Alternatives are
* change it to handle extensions separately/explicitly
* or change its consumers to append extension after it
=> NormalizedFileNames should add prefix instead of suffix

org.jacoco.core.test/pom.xml, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
IMO this visualization on its own and as an addition to #1565 is very handy when
* investigating failures of tests after compiler version update
* adding new tests
* updating existing tests
* and experimenting with implementations of new features such as #1670
For example execution of `org.jacoco.core.test.validation.java8.InterfaceDefaultMethodsTest` after this change generates following report in directory `org.jacoco.core.test.validation.java8/target/reports/InterfaceDefaultMethodsTest/`
=> Generate HTML reports for validation tests

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinSyntheticAccessorsTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinSyntheticAccessorsTarget.kt
We have such [test for Java](https://github.com/jacoco/jacoco/blob/v0.8.12/org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/SyntheticTarget.java), so I think we should add similar for Kotlin too.
=> Add validation test for synthetic accessor methods in Kotlin

.mvn/wrapper/maven-wrapper.properties, org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/build.html, org.jacoco.doc/docroot/doc/changes.html, org.jacoco.doc/docroot/doc/environment.html
After #1707 we do not need to rely on pre-installed Maven version in CI or on a developer machine, so I don't see any reason not to require latest Maven version, which is 3.9.9 as of today. Together with #1701 this will help reduce time required to handle updates of Maven and its plugins since compatibility/requirements matrix becomes much simpler.
=> Require at least Maven 3.9.9 for build

.idea/codeStyles/Project.xml, .idea/codeStyles/codeStyleConfig.xml, .idea/eclipseCodeFormatter.xml, .idea/externalDependencies.xml
* `.idea/externalDependencies.xml` to require installation of EclipseCodeFormatter plugin into IntelliJ IDEA
* `.idea/eclipseCodeFormatter.xml` configures plugin to use the same settings as for Eclipse IDE and spotelss-maven-plugin
* `.idea/codeStyles/codeStyleConfig.xml` and `.idea/codeStyles/Project.xml` prevent use of wildcard imports
----
After import of project with this change into a fresh installation of IntelliJ IDEA 2024.2.1:
After installation of EclipseCodeFormatter plugin:
=> Add configuration files for Java code formatting in IntelliJ IDEA

org.jacoco.doc/pom.xml
`reportOutputDirectory` parameter was removed in maven-javadoc-plugin
version 3.10.0 by
https://github.com/apache/maven-javadoc-plugin/commit/9638a6a76c6db53c3bf8ffbd5cec7318b0e25303
(https://issues.apache.org/jira/browse/MJAVADOC-785).
This was overlooked in commit 435579f27cb8259ba14c1a868245a843e053211f.
`outputDirectory` parameter can be used to restore prior behavior,
but this customization seems unnecessary.
=> Fix warning "'reportOutputDirectory' is unknown for plugin 'maven-javadoc-plugin:3.11.1:jar (attach-javadocs)'"

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinWhenEnumTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinWhenSealedTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinWhenStringTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenEnumTarget.kt, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenSealedTarget.kt, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenStringTarget.kt
It already contains a lot of different cases.
#1756, #1769, and #1773 will add even more.
So I propose to split it.
=> Split KotlinWhenExpressionTarget

org.jacoco.core.test/src/org/jacoco/core/test/perf/ExecuteInstrumentedCodeScenario.java, org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java, org.jacoco.core/src/org/jacoco/core/internal/instr/ClassInstrumenter.java
=> Fix typo: replace "a instrumented" by "an instrumented"

org.jacoco.report/src/org/jacoco/report/internal/xml/XMLElement.java
"a" should be used instead of "an" when the
following word doesn't start with a vowel sound.
=> Fix typo: replace "an child" by "a child"

org.jacoco.doc/pom.xml
Without this change execution of `mvn verify` produces
```
[INFO] --- antrun:3.1.0:run (prepare-reports) @ org.jacoco.doc ---
[INFO] Executing tasks
[WARNING]      [echo] JUnit report
[INFO]     [mkdir] Created dir: /Users/godin/projects/jacoco/jacoco/org.jacoco.doc/target/junit
[INFO] [junitreport] Processing /Users/godin/projects/jacoco/jacoco/org.jacoco.doc/target/junit/TESTS-TestSuites.xml to /Users/godin/projects/jacoco/jacoco/org.jacoco.doc/target/junit/junit-noframes.html
[INFO] [junitreport] Loading stylesheet /Users/godin/projects/jacoco/jacoco/org.jacoco.doc/xsl/junit-noframes.xsl
[INFO] [junitreport] Transform time: 149ms
[INFO]      [move] Moving 1 file to /Users/godin/projects/jacoco/jacoco/org.jacoco.doc/target/junit
[INFO] Executed tasks
```
According to …
=> Build should not produce warning about generation of JUnit report

.github/workflows/ci.yml, org.jacoco.ant.test/src/org/jacoco/ant/SecurityManagerTest.xml
Unfortunately I overlooked this during review of #1780 😞
Fortunately on one of my dev machines order of tests is different than in our CI 😄 and build started to fail after merge
```
testJaCoCoWithSecurityManager:
[jacoco:coverage] Enhancing java with coverage
[java] WARNING: A command line option has enabled the Security Manager
[java] WARNING: The Security Manager is deprecated and will be removed in a future release
[java] Error: Could not find or load main class org.jacoco.ant.TestTarget
[java] Caused by: java.lang.ClassNotFoundException: org.jacoco.ant.TestTarget
```
Problem can be reproduced by executing only `SecurityManagerTest`
```
mvn verify -Dtest=SecurityManagerTest -DfailIfNoTests=false
```
or by changing order of tests
```
mvn verify -Dsurefire.runOrder=reversealphabetical …
```
=> SecurityManagerTest should not depend on CoverageTaskTest

org.jacoco.core/src/org/jacoco/core/data/ExecutionDataStore.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/MethodCoverageCalculator.java, org.jacoco.report/src/org/jacoco/report/internal/xml/XMLElement.java
=> Fix typo: replace "a instance" by "an instance"

org.jacoco.core/src/org/jacoco/core/data/ExecutionDataReader.java, org.jacoco.core/src/org/jacoco/core/runtime/RemoteControlReader.java
"a" should be used instead of "an" when the
following word doesn't start with a vowel sound.
=> Fix typo: replace "an listener" by "a listener"

org.jacoco.core/src/org/jacoco/core/internal/analysis/SourceNodeImpl.java
This was overlooked in commit 831ecd609e17a3a5f8e114134fa0ce1d2071c6bd.
=> Fix javadoc doclint warning "no @param for fragment"

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinWhenSealedTarget.kt
For `Example.kt`
```Kotlin
sealed class Sealed {
object Sealed1 : Sealed()
object Sealed2 : Sealed()
}
fun example(sealed: Sealed) {
when (sealed) {
is Sealed.Sealed1 -> println("case 1")
is Sealed.Sealed2 -> println("case 2")
}
}
fun main() {
example(Sealed.Sealed1)
example(Sealed.Sealed2)
}
```
Using Kotlin compiler version `2.0.0` execution of
```
kotlin-compiler-2.0.0/bin/kotlinc Example.kt -d classes
javap -v -p classes/ExampleKt.class
java \
-javaagent:jacoco-0.8.12/lib/jacocoagent.jar \
-cp kotlin-compiler-2.0.0/lib/kotlin-stdlib.jar:classes \
ExampleKt
java \
-jar jacoco-0.8.12/lib/jacococli.jar \
report jacoco.exec \
--classfiles classes \
--sourcefiles . \
--html report
```
produces
```
public static final void example(Sealed);
descriptor: (LSealed;)V
flags: (0x0019) ACC_PUBLIC, …
```
=> Add validation test for Kotlin `when` statement with `sealed class` subject type

org.jacoco.doc/docroot/doc/ant.html, org.jacoco.report/src/org/jacoco/report/internal/xml/ReportElement.java, org.jacoco.report/src/org/jacoco/report/internal/xml/XMLElement.java
=> Fix typo: replace "a XML" by "an XML"

org.jacoco.core.test/src/org/jacoco/core/internal/instr/LocalProbeArrayStrategyTest.java
We already have dedicated unit tests for other `IProbeArrayStrategy` implementations - see [`NoneProbeArrayStrategyTest`](https://github.com/jacoco/jacoco/blob/v0.8.12/org.jacoco.core.test/src/org/jacoco/core/internal/instr/NoneProbeArrayStrategyTest.java) and [`CondyProbeArrayStrategyTest`](https://github.com/jacoco/jacoco/blob/v0.8.12/org.jacoco.core.test/src/org/jacoco/core/internal/instr/CondyProbeArrayStrategyTest.java).
=> Add unit test for LocalProbeArrayStrategy

org.jacoco.examples/src/org/jacoco/examples/ReportGenerator.java, org.jacoco.report/src/org/jacoco/report/internal/html/IHTMLReportContext.java, org.jacoco.report/src/org/jacoco/report/internal/html/index/ElementIndex.java
=> Fix typo: replace "a HTML" by "an HTML"

org.jacoco.agent.rt/src/org/jacoco/agent/rt/internal/Agent.java, org.jacoco.core/src/org/jacoco/core/runtime/AgentOptions.java
=> Fix typo: replace "a agent" by "an agent"

org.jacoco.core.test/src/org/jacoco/core/internal/instr/ClassFieldProbeArrayStrategyTest.java
We already have dedicated unit tests for other `IProbeArrayStrategy` implementations - see [`NoneProbeArrayStrategyTest`](https://github.com/jacoco/jacoco/blob/v0.8.12/org.jacoco.core.test/src/org/jacoco/core/internal/instr/NoneProbeArrayStrategyTest.java) and [`CondyProbeArrayStrategyTest`](https://github.com/jacoco/jacoco/blob/v0.8.12/org.jacoco.core.test/src/org/jacoco/core/internal/instr/CondyProbeArrayStrategyTest.java). And recently added [`InterfaceFieldProbeArrayStrategyTest`](https://github.com/jacoco/jacoco/pull/1792).
=> Add unit test for ClassFieldProbeArrayStrategy

org.jacoco.core/src/org/jacoco/core/analysis/CounterComparator.java, org.jacoco.core/src/org/jacoco/core/analysis/NodeComparator.java, org.jacoco.core/src/org/jacoco/core/data/IncompatibleExecDataVersionException.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassCoverageImpl.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinGeneratedFilter.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinSMAP.java
This fixes warnings added in JDK 15,
so that build of `org.jacoco.core` is doclint warnings free with JDK versions from 15 to 17,
I'll raise separate PRs for other modules and warnings introduced in later JDK versions.
=> Fix javadoc doclint warnings "no comment"

.github/dependabot.yml, jacoco-maven-plugin.test/pom.xml, org.jacoco.build/pom.xml, org.jacoco.examples.test/pom.xml
Without this change execution of
```
mvn verify -Dmaven.plugin.validation=verbose
```
produces
```
[WARNING]   Plugin EXTERNAL issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
```
=> Upgrade maven-invoker-plugin to 3.8.1

org.jacoco.core.test/src/org/jacoco/core/instr/MethodRecorder.java, org.jacoco.core.test/src/org/jacoco/core/internal/flow/MethodSanitizerTest.java, org.jacoco.core.test/src/org/jacoco/core/internal/instr/ClassFieldProbeArrayStrategyTest.java
As a follow-up from the previously added new tests I propose to add a new convenience method to the test utils to directly obtain a `MethodRecoder` instance from an existing `MethodNode`.
=> Add convenience method for asserting MethodNodes

org.jacoco.core.test/src/org/jacoco/core/internal/instr/InterfaceFieldProbeArrayStrategyTest.java
Looking at
https://github.com/jacoco/jacoco/blob/dbfb6f2ad904158b5b40a93fea222e263aeaf9ab/org.jacoco.core.test/src/org/jacoco/core/internal/instr/ProbeArrayStrategyFactoryTest.java#L201-L209
one might think that case of update of existing `clinit` method by `InterfaceFieldProbeArrayStrategy` is tested,
but looking at code coverage report
and after replacement of condition
https://github.com/jacoco/jacoco/blob/dbfb6f2ad904158b5b40a93fea222e263aeaf9ab/org.jacoco.core/src/org/jacoco/core/internal/instr/InterfaceFieldProbeArrayStrategy.java#L89
on `if (true)` unit tests still pass, whereas should not. And validation tests fail with
```
java.lang.ClassFormatError: Duplicate method name "<clinit>" with signature "()V" in class file org/jacoco/core/test/validation/java8/targets/InterfaceDefaultMe …
```
=> Add unit test for InterfaceFieldProbeArrayStrategy

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinExceptionsTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinExceptionsTarget.kt
We have such [test for Java](https://github.com/jacoco/jacoco/blob/v0.8.12/org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/targets/ExceptionsTarget.java), so I think we should add similar for Kotlin too.
=> Add validation test for exception based control flow in Kotlin

.idea/codeInsightSettings.xml
Without this change IntelliJ shows me first
`jdk.internal.org.objectweb.asm.Opcodes`
in the list of suggestions and only then
`org.objectweb.asm.Opcodes`.
=> IntelliJ IDEA should not suggest import of `jdk.internal.*` classes

org.jacoco.core.test/src/org/jacoco/core/internal/analysis/CounterImplTest.java
Constructors of primitive wrappers
are deprecated since Java 9
* https://bugs.openjdk.org/browse/JDK-8176335
* https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Integer.html#%3Cinit%3E(int)
and deprecated for removal since Java 16
* https://bugs.openjdk.org/browse/JDK-8252180
* https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Integer.html#%3Cinit%3E(int)
=> Use `Integer.valueOf` instead of deprecated constructor

.azure-pipelines/maven-settings.xml
See https://community.sonarsource.com/t/deprecating-sonar-login-and-sonar-password-in-favor-of-sonar-token/95829
=> Use `sonar.token` instead of deprecated `sonar.login`

.github/dependabot.yml, org.jacoco.build/pom.xml
Nothing suspicious in diffs - here is example for `org.jacoco.core`:
```diff
--- 1/before/jacoco-0.8.13.202412210239/lib/org.jacoco.core-0.8.13.202412210239/META-INF/MANIFEST.MF
+++ 2/after/jacoco-0.8.13.202412210238/lib/org.jacoco.core-0.8.13.202412210238/META-INF/MANIFEST.MF
@@ -1,10 +1,8 @@
Manifest-Version: 1.0
-Created-By: Apache Maven Bundle Plugin
+Created-By: Apache Maven Bundle Plugin 6.0.0
Build-Jdk-Spec: 21
Automatic-Module-Name: org.jacoco.core
-Bnd-LastModified: 1734748801910
-Build-Jdk: 21.0.1
-Built-By: godin
+Bnd-LastModified: 1734748691882^M
Bundle-Description: JaCoCo Core
Bundle-License: https://www.eclipse.org/legal/epl-2.0/
Bundle-ManifestVersion: 2
@@ -12,9 +10,9 @@ Bundle-Name: JaCoCo Core
Bundle-RequiredExecutionEnvironment: J2SE-1.5
Bundle-SymbolicName: …
```
=> Upgrade maven-bundle-plugin to 6.0.0

org.jacoco.build/pom.xml
This was overlooked in 4e159f7b351f8038bd72a0813445a427d62586b3.
To avoid this mistake in the future, check of license headers should use the same variable.
=> Update copyright year in variable used for generation of documentation

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinSafeCallOperatorTarget.kt, org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinSafeCallOperatorFilterTest.java, org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinSafeCallOperatorFilter.java, org.jacoco.doc/docroot/doc/changes.html
Prior to #1810
However after
----
```
public static final java.lang.String example(org.example.A);
descriptor: (Lorg/example/A;)Ljava/lang/String;
flags: (0x0019) ACC_PUBLIC, ACC_STATIC, ACC_FINAL
Code:
stack=2, locals=4, args_size=1
0: aload_0
1: dup
2: ifnull        27
5: astore_1
6: aload_1
7: astore_2
8: iconst_0
9: istore_3
10: invokestatic  #16                 // Method exception:()V
13: aload_1
14: invokevirtual #22                 // Method org/example/A.getB:()Lorg/example/B;
17: dup
18: ifnull        27
21: invokevirtual #28                 // Method org/example/B.getC:()Ljava/lang/String;
24: goto          29
27: pop
28: aconst_null
29: areturn
```
branch `0` of `ifnull` instructions of a chain should not be replaced.
=> Improve KotlinSafeCallOperatorFilter for the cases when chain of safe call operators throws exception

org.jacoco.build/pom.xml, org.jacoco.doc/docroot/doc/repo.html
Part of #1896 
https://central.sonatype.org/publish/publish-portal-snapshots/#publishing-via-other-methods
----
https://central.sonatype.com/service/rest/repository/browse/maven-snapshots/org/jacoco/jacoco/
=> Migrate publishing of snapshot to the Central Publisher Portal

org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinCrossinlineTest.java, org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinCrossinlineTarget.kt, org.jacoco.core.test/src/org/jacoco/core/test/InstrumentingLoader.java, org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
`KotlinCrossinlineTest` did not caught regression in Kotlin compiler version 2.0
* https://github.com/jacoco/jacoco/issues/1840
* https://youtrack.jetbrains.com/issue/KT-74617/Trivial-SMAP-optimization-leads-to-missing-debug-info-after-inline
because `ValidationTestBase` does not analyse non executed classes,
and for `KotlinCrossinlineTarget.kt` Kotlin compiler produces
```
KotlinCrossinlineTarget$example$1$1.class
KotlinCrossinlineTarget$example$1.class
KotlinCrossinlineTarget$main$$inlined$example$1$1.class
KotlinCrossinlineTarget$main$$inlined$example$1.class
KotlinCrossinlineTarget.class
```
where first two are not executed, however should provide SMAP essential for proper analysis.
This change allows `KotlinCrossinlineTest` to catch this regression and needed for [update of Kotlin …
=> Fix KotlinCrossinlineTest

jacoco-maven-plugin/pom.xml
This version of `org.apache.maven.shared:file-management` upgrades `commons-io:commons-io` which fixed [CVE-2024-47554](https://avd.aquasec.com/nvd/2024/cve-2024-47554/)
=> Bump org.apache.maven.shared:file-management from 3.1.0 to 3.2.0

org.jacoco.build/pom.xml
Part of #1896
https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#plugins-tested-for-compatibility
=> Migrate release staging to the Central Publisher Portal
