jacoco/jacoco

- .travis.sh
- .travis.yml
- .travis/toolchains.xml
> Build with JDK 5 in Travis

- .travis.sh
- .travis/settings.xml
> Deployment of snapshots from Travis

- org.jacoco.core.test/src/org/jacoco/core/analysis/CoverageBuilderTest.java
- org.jacoco.core/src/org/jacoco/core/analysis/CoverageBuilder.java
> Don't count class stats twice for a package

- org.jacoco.core.test/src/org/jacoco/core/runtime/AgentOptionsTest.java
- org.jacoco.core/src/org/jacoco/core/runtime/AgentOptions.java
Fix for regression caused by fix for #358
> AgentOptions should handle invalid args properly

- .github/ISSUE_TEMPLATE.md
Use new issue template feature of GitHub:
https://help.github.com/articles/creating-an-issue-template-for-your-repository/
> Add issue template to JaCoCo repository

- .appveyor.yml
- .travis/appveyor-toolchains.xml
It would be nice to have a CI build on all JaCoCo pull request. To allow testing for early adopters artifacts should be downloadable.
> Publish artifact for pull requests

- org.jacoco.doc/docroot/doc/build.html
- org.jacoco.doc/docroot/doc/conventions.html
- org.jacoco.doc/docroot/doc/environment.html
The development tools and process actually used has changed over the time. This should be reflected in the developer documentation
> Update developer documentation

- org.jacoco.ant/META-INF/MANIFEST.MF
- org.jacoco.build/pom.xml
- org.jacoco.core.test/META-INF/MANIFEST.MF
- org.jacoco.core.test/src/org/jacoco/core/internal/instr/DuplicateFrameEliminatorTest.java
- org.jacoco.core/META-INF/MANIFEST.MF
- org.jacoco.doc/docroot/doc/changes.html
- org.jacoco.examples/META-INF/MANIFEST.MF
- org.jacoco.report/META-INF/MANIFEST.MF
http://asm.ow2.org/history.html
> Upgrade to ASM 5.1

- org.jacoco.doc/docroot/doc/maven.html
> Add note about explicit selection of non-aggregate reports

- org.jacoco.doc/docroot/doc/faq.html
It seems to be a common mistake to instrument classes offline but not to add jacocoagent.jar.
> Add FAQ entry about offline instrumentation

- jacoco-maven-plugin/src/org/jacoco/maven/AgentMojo.java
- org.jacoco.doc/docroot/doc/maven.html
Add hints for the issues faced during integration of JaCoCo with [Eclipse Collections](http://www.eclipse.org/collections/). 
Eclipse Collections Pull Request: https://github.com/eclipse/eclipse-collections/pull/166
> Add hints about surefire-plugin and argLine.

- jacoco-maven-plugin.test/it/it-report-aggregate/report/pom.xml
- jacoco-maven-plugin/src/org/jacoco/maven/ReportAggregateMojo.java
- org.jacoco.doc/docroot/doc/changes.html
Just a follow up to #498 to update documentation.
> Finalize documentation for PR #498

- .gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/jacoco/jacoco/510)
> add intellij files to ignore

- org.jacoco.core.test/src/org/jacoco/core/test/validation/ExceptionsTest.java
Currently there are failures of tests with JDK 8u152 EA b05 due to [JDK-8180660](https://bugs.openjdk.java.net/browse/JDK-8180660).
> Fix assertions for JDK 8 >= u152

- org.jacoco.agent.rt.test/src/org/jacoco/agent/rt/internal/AgentTest.java
* Don't write to file system
* Avoid DNS lookups (slows down builds)
* Use new test naming conventions
> Cleanup AgentTest

- org.jacoco.doc/docroot/doc/changes.html
Fixes #631 - Looks like the hub magic stopped working.
> Consolidate Change Log for 0.8.0 Release

- jacoco-maven-plugin/pom.xml
> Update version of commons-collections in jacoco-maven-plugin

- .travis.sh
- org.jacoco.doc/docroot/doc/environment.html
> Re-enable SonarQube analysis and fix link on its results

- org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/filter/FinallyTest.java
- org.jacoco.core.test/src/org/jacoco/core/test/validation/Source.java
- org.jacoco.core.test/src/org/jacoco/core/test/validation/SourceTest.java
- org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
As discussed in https://github.com/jacoco/jacoco/pull/709#discussion_r202812090
> Validation tests should use source filename from coverage results

- org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinUnsafeCastOperatorTest.java
- org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinUnsafeCastOperatorTarget.kt
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinUnsafeCastOperatorFilterTest.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/Filters.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinUnsafeCastOperatorFilter.java
- org.jacoco.doc/docroot/doc/changes.html
> Add filter for Kotlin "unsafe" cast operator

- org.jacoco.build/pom.xml
- org.jacoco.core.test.validation.groovy/pom.xml
- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/GroovyDataClassTest.java
- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/targets/GroovyDataClassTarget.groovy
- org.jacoco.core.test.validation/pom.xml
- org.jacoco.doc/docroot/doc/build.html
Code developed during Hackergarten Bern August 2018 with @marchof
> Initial groovy validation setup

- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/MethodAnalyzerTest.java
> Fix MethodAnalyzerTest

- org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/KotlinNotNullOperatorTest.java
- org.jacoco.core.test.validation.kotlin/src/org/jacoco/core/test/validation/kotlin/targets/KotlinNotNullOperatorTarget.kt
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinNotNullOperatorFilterTest.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/Filters.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinNotNullOperatorFilter.java
- org.jacoco.doc/docroot/doc/changes.html
https://groups.google.com/d/msg/jacoco/V4z41kgUnK8/JbqDkAZ5FgAJ
> Add filter for Kotlin not-null assertion operator

- org.jacoco.build/pom.xml
- org.jacoco.core.test.validation/pom.xml
Fixes problem with compilation for bytecode 9+
> Upgrade maven-plugin-plugin and maven-shade-plugin

- org.jacoco.doc/docroot/doc/changes.html
Based on https://github.com/jacoco/jacoco/issues/831#issuecomment-455266249
> Improve wording

- org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java
- org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java
- org.jacoco.doc/docroot/doc/changes.html
> module-info.class should be excluded from analysis

- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/GroovyAutoCloneClassTest.java
- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/targets/GroovyAutoCloneClassTarget.groovy
implemented during hackergarten Zurich.
Test fails because of https://issues.apache.org/jira/browse/GROOVY-9051
> Add validation test for groovy.transform.AutoClone

- org.jacoco.core.test.validation.groovy/pom.xml
- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/GroovyDelegateClassTest.java
- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/targets/GroovyDelegateClassTarget.groovy
Added integration test case for groovy support during Hackergarten Zurich.
Test fails, issue reported at https://issues.apache.org/jira/browse/GROOVY-9051
> Add validation test for groovy.lang.Delegate

- org.jacoco.core.test.validation.groovy/.classpath
- org.jacoco.core.test.validation.groovy/.project
To at least make the project visible in the workspace.
> Add minimal project configuration for Eclipse

- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/GroovySortableClassTest.java
- org.jacoco.core.test.validation.groovy/src/org/jacoco/core/test/validation/groovy/targets/GroovySortableClassTarget.groovy
The test is currently failing and an appropriate issue is open at
https://issues.apache.org/jira/browse/GROOVY-9125
> Add validation test for groovy.transform.Sortable

- org.jacoco.build/pom.xml
- org.jacoco.core.test.validation.scala/.classpath
- org.jacoco.core.test.validation.scala/.project
- org.jacoco.core.test.validation.scala/pom.xml
- org.jacoco.core.test.validation.scala/src/org/jacoco/core/test/validation/scala/ScalaSingletonObjectTest.java
- org.jacoco.core.test.validation.scala/src/org/jacoco/core/test/validation/scala/targets/ScalaSingletonObjectTarget.scala
- org.jacoco.core.test.validation/pom.xml
This should not be considered as my/our commitment to implement filters for Scala - this is just to prepare ground for possible contributions.
> Add module for validation tests for Scala

- org.jacoco.doc/docroot/doc/integrations.html
- Fix broken links
- Visual Studio Team Services is now Azure DevOps
- Add STAMP research project
> Update integration matrix

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/1_question.md
- .github/ISSUE_TEMPLATE/2_bug_report.md
- .github/ISSUE_TEMPLATE/3_feature_request.md
* Add CLI
* Make clear that other tools are not supported here
* Ask for executable reproducer
* Ask for full stack trace
* Clarify rule about closing issues as invalid
> Update issue templates

- jacoco-maven-plugin.test/it/setup-parent/pom.xml
- org.jacoco.build/pom.xml
- org.jacoco.examples/build/pom.xml
This closes #1102 , closes #1103 , and closes #1104
> Upgrade JUnit to 4.13.1

- org.jacoco.core.test.validation.java5/src/org/jacoco/core/test/validation/java5/SyntheticTest.java
It was lost in 1001adda9a37f262c6162c1fec99487a5a79e7fa
> Add missing annotation Test

- org.jacoco.doc/docroot/doc/changes.html
Discovered by @LorenzoBettini - https://twitter.com/lorenzo_bettini/status/1390691281286860807
> Fix typo in changelog

- org.jacoco.build/licenses/asm-9.4.html
- org.jacoco.build/pom.xml
- org.jacoco.doc/docroot/doc/changes.html
> Upgrade ASM to 9.4

- .azure-pipelines/azure-pipelines.yml
- org.jacoco.build/pom.xml
- org.jacoco.core.test.validation/pom.xml
- org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java
- org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/instr/InstrSupportTest.java
- org.jacoco.core/src/org/jacoco/core/internal/instr/InstrSupport.java
- org.jacoco.doc/docroot/doc/build.html
- org.jacoco.doc/docroot/doc/changes.html
- org.jacoco.doc/docroot/doc/environment.html
- org.jacoco.doc/docroot/doc/faq.html
> Add official support for Java 20, experimental for Java 21

- jacoco-maven-plugin/pom.xml
> Update plexus-utils to 3.0.24

- org.jacoco.build/pom.xml
This reduces number of warnings produced by Maven 3.9.2
```
[INFO] Total time:  02:00 min
[INFO] Finished at: 2023-05-15T10:26:59+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 24 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:2.4.1
[WARNING]  * org.apache.maven.plugins:maven-javadoc-plugin:3.0.1
[WARNING]  * …
```
> Upgrade maven-clean-plugin to 3.2.0

- org.jacoco.build/pom.xml
This reduces number of warnings produced by Maven 3.9.2
```
[INFO] Total time:  02:00 min
[INFO] Finished at: 2023-05-15T10:26:59+02:00
[WARNING]
[WARNING] Plugin validation issues were detected in 24 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-clean-plugin:2.4.1
[WARNING]  * org.apache.maven.plugins:maven-javadoc-plugin:3.0.1
[WARNING]  * …
```
> Upgrade maven-install-plugin to 3.1.1

- org.jacoco.build/licenses/asm-9.6.html
- org.jacoco.build/pom.xml
- org.jacoco.doc/docroot/doc/changes.html
> Update ASM to 9.6

- org.jacoco.doc/docroot/doc/integrations.html
> Add Skippy to the list of third-party integrations

- org.jacoco.core.test.validation.scala/pom.xml
- org.jacoco.core.test.validation/pom.xml
> Upgrade Scala to 2.13.12

- .github/workflows/ci.yml
In continuation of #1569 and #1572
> Add builds with ECJ to GitHub Actions

- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/ClassAnalyzerTest.java
It was forgotten in commit 281538bc74d9f09f5b0d83250a4435b5c2732e21
> Add missing test

- org.jacoco.core.test/src/org/jacoco/core/internal/instr/CondyProbeArrayStrategyTest.java
It was forgotten in commit 36b4e9c7103441d556a1667b4485960f5bdfeff8
> Add missing javadoc

- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/ClassAnalyzerTest.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/ClassAnalyzer.java
This was overlooked in commit 4d4d02e6dbfb17f454bf4579ee13209e9f035154
> Fix ClassAnalyzerTest

- .mvn/wrapper/maven-wrapper.properties
See https://maven.apache.org/wrapper/#checksum-verification-of-downloaded-binaries
> Enable checksum verification of Maven distribution

- org.jacoco.core.test/src/org/jacoco/core/test/validation/ValidationTestBase.java
As an addition/continuation of #1690 and #1565:
TEXTified representation is useful when
* investigating failures of validation tests after compiler version update
* adding new tests
* updating existing tests
* and experimenting with implementations of new features
ASMified representation is useful for the creation of unit tests based on validation tests.
> Validation tests should create ASMified and TEXTified bytecode representations

- org.jacoco.ant.test/pom.xml
- org.jacoco.ant.test/src/org/jacoco/ant/CoverageTaskTest.xml
- org.jacoco.ant.test/src/org/jacoco/ant/InstrumentTaskTest.xml
- org.jacoco.ant.test/src/org/jacoco/ant/SecurityManagerTest.java
- org.jacoco.ant.test/src/org/jacoco/ant/SecurityManagerTest.xml
- org.jacoco.ant.test/src/org/jacoco/ant/empty.xml
> Do not test with SecurityManager when Java version 24 and above

- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultMethodsFilterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinEnumFilterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinGeneratedFilterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinInlineClassFilterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilterTest.java
- org.jacoco.core.test/src/org/jacoco/core/internal/analysis/filter/KotlinUnsafeCastOperatorFilterTest.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/FilterSet.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/Filters.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinComposeFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinCoroutineFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultArgumentsFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinDefaultMethodsFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinEnumFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinGeneratedFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineClassFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinInlineFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinSafeCallOperatorFilter.java
- org.jacoco.core/src/org/jacoco/core/internal/analysis/filter/KotlinUnsafeCastOperatorFilter.java
Hi @Godin, this is a proposal how we could group the filters. We may move one step further and put filters in separate sub-packages (Java/Kotlin).
> Restructure filter grouping

- org.jacoco.core.test/src/org/jacoco/core/analysis/AnalyzerTest.java
- org.jacoco.core.test/src/org/jacoco/core/instr/InstrumenterTest.java
- org.jacoco.core/src/org/jacoco/core/analysis/Analyzer.java
- org.jacoco.core/src/org/jacoco/core/instr/Instrumenter.java
- org.jacoco.doc/docroot/doc/changes.html
> Provide context information when zip reading throws IllegalArgumentException

- org.jacoco.build/licenses/asm-9.8.html
- org.jacoco.build/pom.xml
- org.jacoco.doc/docroot/doc/changes.html
https://github.com/jacoco/jacoco/issues/1862
> Update to ASM 9.8

- .azure-pipelines/azure-pipelines.yml
- .github/workflows/ci.yml
See https://github.com/actions/runner-images/issues/11101
> Use Ubuntu 24.04

- org.jacoco.core.test.validation.scala/pom.xml
See https://groups.google.com/g/jacoco/c/jCL-h0KzjD0/m/azNfroMRAQAJ
> Upgrade scala-maven-plugin to 4.5.6
